### ISSUE TITLE
Full Citation as "NAME" Property in Notion

### ISSUE THREAD

**Issue by testaweiser** [dvanoni/notero#100]
**Describe the solution you'd like**
Thanks for the brilliant Zotero to Notion plugin! 
I would like to show Zotero "Full Citation" in the Notion "Name" Property. Then View ONLY Full Citations as a List (i.e. bibliography). 

**Describe alternatives you've considered**
Notion requires the Name Property and it cannot be deleted. I've tried to copy and paste the Full Citation into the Name Property but that's a lot of work, and creates confusion with the Zotero to Notion sync feature.

**Comment by dvanoni** [comment]
Hi @testaweiser, thanks for this input! This sounds related to #14, and I should definitely be able to include "Full Citation" as one of the options to use for the name. I'll post an update when this functionality is available!

**Comment by dvanoni** [comment]
Hi again @testaweiser!

I just released a test build over on #14 that allows you to select which field to use as the title of Notion pages, and "Full Citation" is one of the options. Would you be interested in downloading the test build to see if it meets your needs?

Thanks!

**Comment by testaweiser** [comment]
Absolutely! I just added on Monday's To-Do list :) Thank you for sharing the update!

**Comment by testaweiser** [comment]
100% success! Love the Notero workflow, thank you @dvanoni
