### ISSUE TITLE
Editors also added as authors

### ISSUE THREAD

**Issue by neeldhara** [dvanoni/notero#11]
I had a Zotero entry with authors and editors like so:

<img width="314" alt="Screenshot 2021-11-06 at 7 44 24 PM" src="https://user-images.githubusercontent.com/15953732/140612779-e5cf8e83-de8a-4280-8a85-92ba215fc056.png">

and everyone ended up in the author list on Notion :)

Can this be fixed please? 

PS. Thank you for the brilliant plugin, I'm using it a LOT!

**Comment by dvanoni** [comment]
Hi @neeldhara, thanks for the feedback!

I believe this should be fixable. Would it be beneficial to have an _Editors_ property in Notion in addition to the current _Authors_ property?

**Comment by neeldhara** [comment]
Yes indeed, that would be great - thank you!

**Comment by dvanoni** [comment]
@neeldhara this has just been fixed in version 0.2.1! The `Authors` property will now only sync actual authors from Zotero. You can also add a new `Editors` property to your Notion database, and that will sync the editors from Zotero as well.

Let me know how this works for you!
