### ISSUE TITLE
Syncing issues

### ISSUE THREAD

**Issue by anastasiaster** [dvanoni/notero#110]
Hi. Documents do not sync from zotero to notion. I think I did everything right. However, when I add the integration token and database ID in the notero preferences on zotero, no sync preferences come up. Could you please help me?

**Comment by anastasiaster** [comment]
Hi. I worked it out. You need to start off with an empty folder in Zotero and only when all the settings are done, drag the files from your main library into it.

**Comment by dvanoni** [comment]
Hi @anastasiaster, thanks for sharing your experience! Several people have asked this same question, so I think I need to update the readme to make this more clear.

If you'd like to sync items without having to create a new Zotero folder, you can achieve this by using a temporary tag. See the instructions and video in the [How to bulk sync existing items](https://github.com/dvanoni/notero#how-to-bulk-sync-existing-items) section of the readme.

There's also a planned enhancement that will make this easier as well: #21

**Comment by anastasiaster** [comment]
Thank you for all your help! Keep up the great work!
