### ISSUE TITLE
APIRespnseError: Invalid request URL

### ISSUE THREAD

**Issue by amidice** [dvanoni/notero#116]
Hi dvanoni,
I included the basic Notero template into my existing database, however this error Invalid request URL kept showing up. Just wondering if you know how to fix it. Thank you so much for developing this!

**Comment by dvanoni** [comment]
Hi @amidice, thanks for reaching out! Would you mind sharing the value of the **Database ID** field you currently have entered in the Notero Preferences? That error message typically means there's something off with the Database ID.

**Comment by amidice** [comment]
@dvanoni, Thanks a lot for reaching out and pointing out where went wrong. It's because I used the 32-character string after "v=" instead the string before "?", once fix this, it's working very well. Thank you a lot!
