### ISSUE TITLE
Could you please add which journal was the paper published in and citation numbers of the specific paper metrics? Thanks!

### ISSUE THREAD

**Issue by amidice** [dvanoni/notero#118]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dvanoni** [comment]
Hi @amidice, thanks for the feedback. Adding journal as a property has been asked about previously in #52, so that's definitely on the todo list.

Could you explain more about the following? Could you share a screenshot of this information in Zotero?

> citation numbers of the specific paper metrics

**Comment by amidice** [comment]
@dvanoni Hi dvanoni, thanks for your response. It's an add-on feature for Zotero just like Noterom, it simply pulls up citation counts from google scholar, the github page is here https://github.com/eschnett/zotero-citationcounts
Thanks a lot!

**Comment by dvanoni** [comment]
Hi @amidice! I've just released [v0.5.5](https://github.com/dvanoni/notero/releases/tag/v0.5.5) which adds support for syncing the following properties:

| Property Name | Property Type |
|--------|--------|
| `Date Modified` | Date |
| `Extra` | Text |
| `Place` | Text |
| `Proceedings Title` | Text |
| `Publication` | Text |
| `Series Title` | Text |

The `Publication` property should be equivalent to Journal, and the citation count should be available in the `Extra` property.

I also want to add support for customizing the properties that can be synced. I'm tracking that work in #355, so please follow along there if you're interested!
