### ISSUE TITLE
Title as title

### ISSUE THREAD

**Issue by butzifutz** [dvanoni/notero#14]
Hi, 
first I really love how nice this plugin connects zotero and notion. 
However for me it would be more intuitive to have the actual Title (of the paper or whatever) as the notion property type "Title" rather than "(author et al.,year)". 
Would be nice it this would be more flexible e.g. changeable. Reason: When I link the articles in notion I would search for it I would usually search for the title rather then the author.

**Comment by dvanoni** [comment]
Thanks for the feedback, @butzifutz! This sounds like it relates to #5 in that users would like to be able to configure the citation style that's used as the name of the Notion pages. I think I could make "article title" an additional option for this configuration preference.

**Comment by pmmendoza** [comment]
+1 on this one:
I just also ran into this issue when having two citations of the same authors & year and I couldn't differentiate which one I wanted to link to via the @ in Notion.

**Comment by dgscotia** [comment]
Hi @dvanoni I love the plugin and want to support the possibility to customize the title. I currently have 8 papers/websites/reports from one organization in 2021 and I just can't distinguish them when trying to link, like @pmmendoza said. A change here would be fantastic.

**Comment by josh-ashkinaze** [comment]
Hi, any update on this one? Just want to give another +1! This would increase usability immensely and seems (could be off base) lower effort than some other things on the backlog. And as others have said, thanks so much creating this tool!

**Comment by dvanoni** [comment]
Hi @josh-ashkinaze, thanks for the kind words!

I haven't had a chance to get back into working on this as I've had another project taking up my time, but I'm hoping that will change soon. Once I get some time, I think this issue will probably be at the top of my list. As you said, I do think it's lower effort than other items, and it definitely has a lot of 👍. Stay tuned!

**Comment by qcts33** [comment]
I just find out about this zotero plugin, and I'm loving it.
About the title, I would like to suggest the citation key from Better BibTex as an option.

**Comment by ioool** [comment]
+1 to this topic. 

Thank you for this wonderful plugin (I'm a Zotero and Notion fan), looking forward to start my PhD on september and use it.

**Comment by lilakk** [comment]
@dvanoni This would be a really helpful enhancement, is there any update? And again thank you so much for creating this plugin!

**Comment by dvanoni** [comment]
Hi everyone! I finally had some time to work on this, and I've added a new configuration option into the Notero Preferences that allows you to select which field you'd like to use as the title of pages in Notion. It currently supports the following fields:

- Item Full Citation
- Item In-Text Citation
- Item Short Title
- Item Title

If some folks wouldn't mind downloading the [test build above](https://github.com/dvanoni/notero/issues/14#issuecomment-1214209165) and trying it out, I'd really appreciate your feedback!

![CleanShot 2022-08-13 at 12 16 52@2x](https://user-images.githubusercontent.com/299357/184507838-7f583d9a-19a0-4d93-b257-efb2d8240fc1.png)

**Comment by josh-ashkinaze** [comment]
Hi @dvanoni , great job on the feature enhancement. I tested it out today and had no problems. Once again, thank you so much for your time and effort in creating and maintaining this project!

**Comment by dgscotia** [comment]
Works great, @dvanoni, thank you so much! It would be nice if it would update all items to the new title format without having to make changes in Zotero first to trigger it, but otherwise really great. Thanks!

**Comment by dvanoni** [comment]
Thanks for the feedback, @dgscotia!

I agree that having a way to update all items would be very useful for this. One proposed solution is documented in #21.

**Comment by mwmg** [comment]
Hi @dvanoni, I just started using the plugin and I'm loving it! Thanks for the great work.

I think it would be very useful if you could also add the citation key field as an option, as proposed in #5 . In my case it would make it much easier to copy Notion drafts into LaTeX and convert citations to BibTex.

**Comment by jkhnfk** [comment]
非常感谢作者，解决了一个大问题。不然在文中标记相关文献时非常麻烦。
Thank you very much for solving a big problem. Otherwise, it is very troublesome to mark relevant literature in the text.

**Comment by dvanoni** [comment]
Hey everyone! I wanted to let you know that I released [version 0.4.0](https://github.com/dvanoni/notero/releases/tag/v0.4.0), and it includes a new option in the Notero preferences that lets you use item title as the title of your Notion pages (as show in my [screenshot above](https://github.com/dvanoni/notero/issues/14#issuecomment-1214210231) from a few months ago). I hope this helps with your workflows!

**Comment by dgscotia** [comment]
Thank you so much!

**Comment by ehoffmannfacs** [comment]
Hey @dvanoni , thank you so much for this awesome tool. Our team has a need to sync a Zotero library with an existing database where the primary (title) column would be the article title, and the author information would pull over to a second text property in Notion. I can't seem to get the author information to pull over when I set my Notero preferences to "item title," however. Am I missing something? Thanks so much for any help you can provide.

**Comment by dvanoni** [comment]
Hey @ehoffmannfacs, I'm glad you were able to get the author information to sync. Notero currently only supports a predefined set of database properties that it can sync to, but I'm hoping to make this customizable in the future so that you can name your properties whatever you'd like.

**Comment by ehoffmannfacs** [comment]
That functionality would be great. Thanks so much for your reply.
