### ISSUE TITLE
Notion link attachment is not created

### ISSUE THREAD

**Issue by balopat** [dvanoni/notero#149]
**Describe the issue**
I've been living with duplicated items since I installed Notero, but today I figured I search for a solution. I found #27 - and I think the issue is similar, however, the Notion link attachment never gets created in my case. 

**To Reproduce**

1. Add an item to a synced collection via Zotero Chrome extension/drag n drop a pdf 
2. Notero syncs automatically the first instance and adds the notion tag 
3. As Zotero adds new items (notes, pdf, etc.), it modifies the item
4. Notero syncs again and creates a new, duplicate item in the database for each modification 
5. I have 3 duplicate entries now in Notion

**Expected behavior**
I'd expect a single Notion database record to be maintained for the same Zotero item by creating the Notion link attachment, and not syncing duplicate items before that happens.

**Screenshots**

https://user-images.githubusercontent.com/635073/194908101-82340438-6d0b-4922-aa2c-68a63bbe2fc6.mov

**Additional context**

Zotero add-ons:

![image](https://user-images.githubusercontent.com/635073/194908471-a4951807-c5b0-4c89-90d3-3e1e897658c6.png)

![image](https://user-images.githubusercontent.com/635073/194908559-2bf95314-89b7-43de-88ba-8ca7cc50f3b6.png)

![Screen Shot 2022-10-10 at 12 04 12 PM](https://user-images.githubusercontent.com/635073/194908846-bd768559-5b2a-4be4-b19d-e47afaccecbb.png)

**Comment by dvanoni** [comment]
@balopat, thanks for reporting this issue! I'm not really sure what the cause is.

Would you mind sending me a screenshot of the error console (from the menu **Tools > Developer > Error Console**)? I'm curious if we can see anything going awry in there.

**Comment by balopat** [comment]
![image](https://user-images.githubusercontent.com/635073/207613330-75d98d04-c344-4cb6-a1e2-371dfea93625.png)

and some more

![image](https://user-images.githubusercontent.com/635073/207613387-1eb71f08-0cd9-4452-9531-144b7d20332e.png)

**Comment by balopat** [comment]
Thanks for looking into this, I might be able to do a bit more debugging myself in the coming weeks.

**Comment by dvanoni** [comment]
@balopat, thanks for posting those screenshots. I don't see anything related to Notero in them.

Can you try performing a sync again, and then open the error console and enter `notero` in the **Filter** input at the bottom-left corner of the error console?

**Comment by balopat** [comment]
Those are the only messages that get created after a sync. I.e. I cleared the logs, did a sync and did a screenshot of _all_ the messages. The `notero` filter shows nothing. 

In the meantime, I ran into this: https://github.com/dvanoni/notero/issues/195

**Comment by balopat** [comment]
I added the following lines to `sync-manager.ts` at line 288:

```
    if ('url' in response) {
      await noteroItem.saveNotionLinkAttachment(response.url);
    } else {
      log('no url was sent in response:\n' + JSON.stringify(response), 'error')
    }
```

And got the following message after the sync was done:

```
zotero(3)(+0000003): Notero: no url was sent in response:
{"object":"page","id":"8cf9ab03-4c19-4de4-9fd4-7877f4cbf27a"}
```

It looks like for some reason on my machine the this is the cause why the attachment is not created. Any idea what assumption went wrong? From my minimal digging into the notion client it seems that instead of a `PageObjectResponse`  a smaller, `PartialPageObjectResponse` is returned. And from https://github.com/makenotion/notion-sdk-js#type-guards it seems that consumers of the notion client should guard against partial vs full responses... I just don't understand yet what to do when a partial response comes. Thoughts?

**Comment by balopat** [comment]
AHHH 😵‍💫 

This was the reason: 
 
<img width="511" alt="image" src="https://user-images.githubusercontent.com/635073/209419240-79737d3d-23ca-4fea-a403-8cb4dfb848f9.png">

Now it's all working.

**Comment by balopat** [comment]
Recommendation: throw an actionable error message (e.g. "Cannot create notion attachment, duplicate items will be created. Please ensure that Read content is allowed for the Notero integration at notion.com/my-integrations")  when partial response is returned

**Comment by dvanoni** [comment]
AH! I'm so glad you figured it out!

Yes, I think that's a great suggestion. I'll also update the README to mention the specific capabilities that are required.

Thank you so much for figuring this out!
