### ISSUE TITLE
Syncing between Notion & Zotero has stopped working

### ISSUE THREAD

**Issue by samawelch** [dvanoni/notero#188]
Apologies if this is a known issue already, but I checked the existing issues and couldn't find anything new on it. I last used Notero last Monday. It worked fine, and I was able to synchronise papers into my database. This morning, I tried adding new papers to the monitored folder and they no longer synchronise across. There's no error message or feedback, new papers just don't show up.

I've tried monitoring a new folder, disconnecting and re-connecting the integration. and I've checked the integration token and database ID. 

I've reproduced the issue on two devices (Windows 10 & 11), running whatever the latest version of Notion is, Zotero 6.0.18 and Notero 0.4.0. LibreOffice for Zotero is installed, but I've disabled it (and it's been disabled for a long time). 

Thank you for all your work on notero, and let me know if there's any more information I can provide.

**Comment by dvanoni** [comment]
Hi, @samawelch! Thanks for reaching out. It's curious that no feedback appears.

To help me dig into this, would you mind installing a test build of Notero? I've been working on a new version that reworks some of the internals and adds a bit more logging to help with debugging purposes.

If you wouldn't mind, could you please install [notero-0.4.1-15](https://nightly.link/dvanoni/notero/actions/runs/3682259116/notero-0.4.1-15.zip). Once you've installed that version, please try to sync items and then open the console from the menu: **Tools > Developer > Error Console**

If you could send me a screenshot of the latest messages in the console, I'd appreciate it!

**Comment by samawelch** [comment]
Hi @dvanoni. Thank you for the speedy reply and suggestion. I've installed the updated version you linked, and the syncing works fine - complete with the little message in the bottom right corner of Zotero.

Whatever you did, thank you for your help. I don't know if it's proper etiquette for me to close the issue, so I'll leave it open, but my problem is definitely now solved.

**Comment by dvanoni** [comment]
@samawelch, that's great! I'm not sure what the exact issue was, but I'm glad it's resolved for you. 😄 

I'll be releasing version 0.4.1 soon, and it should be essentially the same as what you have installed now. If Zotero prompts you to update Notero, it should be fine to go ahead and do so.
