### ISSUE TITLE
Deleting a Reference

### ISSUE THREAD

**Issue by berkdemir** [dvanoni/notero#192]
Hi!
Great work. It works flawlessly and so easy to setup. 
One request: When I delete the reference from Zotero, it doesn't delete from Notion. I can imagine it might be hard to get track of which file is deleted. But I believe it might be a good enhancement, if we can find a solution to do this.

**Comment by dvanoni** [comment]
Hi, @berkdemir. Thanks for the input!

There's been discussion about this in #46. Does the approach I proposed there sound like it would work for you?

**Comment by dvanoni** [comment]
Duplicate of #46
