### ISSUE TITLE
APIResponseError: Invalid request URL

### ISSUE THREAD

**Issue by YellowSanity** [dvanoni/notero#193]
APIResponseError: Invalid request URL pop out when I tried to sync from Zotero to Notion.

![image](https://user-images.githubusercontent.com/121093038/208634542-c682a71f-dbd6-49f7-920b-973751b2f034.png)

Below is the error code:
![image](https://user-images.githubusercontent.com/121093038/208634755-11002c0e-429c-4f58-9704-9e04e10d584f.png)

Thanks for the amazing plugin btw!

I reinstalled Notero and recreate a new page in Notion duplicating Notero Advanced database properties and here comes a new error log. 
![image](https://user-images.githubusercontent.com/121093038/208640681-1a9eccc2-259d-4ddb-bfe5-de4ec4fcafa8.png)

**Comment by dvanoni** [comment]
Hi, @YellowSanity. Thanks for reaching out!

This error usually occurs when there's something awry with the database ID. Can you double check that the database ID you've entered in the Notero preferences follows the format described in the [Configure Notion](https://github.com/dvanoni/notero#configure-notion) section of the readme? It should be 32 characters consisting of only numbers and letters.

**Comment by YellowSanity** [comment]
Hi Dvanoni, this is my database ID: https://www.notion.so/c6cff41f1e4a490bbea293f3b87b58e1

**Comment by dvanoni** [comment]
Ah, I think that's the issue. You want to use just the following: `c6cff41f1e4a490bbea293f3b87b58e1`

Let me know if that works!

**Comment by YellowSanity** [comment]
It works! I am so sorry for bothering you for this silly mistake
