### ISSUE TITLE
[Developer setup] zotero-plugin fork npm is not public?

### ISSUE THREAD

**Issue by balopat** [dvanoni/notero#195]
I'm trying to follow the developer setup to do some debugging on https://github.com/dvanoni/notero/issues/149, but I'm getting: 

```
❯ npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@dvanoni/zotero-plugin/1.6.0/957c40a9cfc6c368a3b8f558f6c47e232c57fb56
```

Using `nvm --lts`:

```
Now using node v14.17.6 (npm v6.14.15)
```

**Comment by dvanoni** [comment]
@balopat, thanks for calling this out. I changed the build process in #180 and forgot to update the README accordingly.

Would you mind reviewing the README changes in #196 and letting me know if that gets you up and running? Thanks!

**Comment by balopat** [comment]
In case the permissions on the Github npm repo are not easy to open up,  I tried a workaround to install zotero-plugin locally - and now I have notero running in my zotero dev profile from source, yay! 

instead of `1.6.0`, I switched to a local dependency:

```
        "@dvanoni/zotero-plugin": "file:../zotero-plugin",
```
where ../zotero-plugin is the git clone of your fork with 1.6.0 tag checked out.

Then `npm install -d` on the zotero-plugin project, ensure that all the js files are generated in the bin folder. 
<img width="217" alt="image" src="https://user-images.githubusercontent.com/635073/209418188-ac4de963-488d-474b-8dc0-411b92796d7c.png">

Ensure you have `npm install -d patch-plugin husky` installed and that `./node_modules/.bin' is added to the PATH...
Then `npm ci` works (I _think_, I'll have to test this again)...

Also, one thing would have been helpful to describe too: 

Make sure your zotero-plugin.ini contains this minimal setup (the zotero-plugin readme is helpful but needs a bit of work to understand what is required for notero specifically):

```
[profile]
name = devdev
path = /Users/balopat/Library/Application Support/Zotero/Profiles/devdev

[plugin]
source = /Volumes/Stuff/proj/notero/build
```

**Comment by dvanoni** [comment]
@balopat, that's great! I'm glad you got it working. The approach you used to install `zotero-plugin` from your local system is what I use while working on it.

That's a great suggestion to provide an example for `zotero-plugin.ini`. I'll add that into #196.
