### ISSUE TITLE
Add sync button to context menus

### ISSUE THREAD

**Issue by dvanoni** [dvanoni/notero#21]
As a followup to #10:

* Add a "Sync all to Notion" button to collection context menu
* Add a "Sync to Notion" button to item context menu

**Comment by panyuz** [comment]
from #6 
> Would a "sync to Notion" button as described in #21 solve your use case?

For my use case, adding the sync button would improve the flexibility of the plugin. I think an option should be added for the user to choose between automatic or manual syncing

**Comment by dvanoni** [comment]
> I think an option should be added for the user to choose between automatic or manual syncing

I like this idea. Once a sync button is added, could this be achieved by just unchecking the collections in the Notero preferences that you don't want to automatically sync?

**Comment by panyuz** [comment]
Do you mean, in the Notero preferences :
- collection is selected: Automatic synchronization ( while, Manual synchronization is disabled)
- collection is not selected: Manual synchronization (auto-sync is disabled)

I think it's a viable solution

**Comment by dvanoni** [comment]
@panyuz, good news! This feature has finally been released in [version 0.4.4](https://github.com/dvanoni/notero/releases/tag/v0.4.4). I hope you find it useful!
