### ISSUE TITLE
Set default "Reading Status" for items directed added to Zotero

### ISSUE THREAD

**Issue by nonPointer** [dvanoni/notero#211]
The templates (journal article, book and book chapter) only work when manually adding a record in the Zotero workspace. Currently, there is no option to specify the default "reading status" for items that are synced from Zotero.

**Comment by nonPointer** [comment]
Context: I saved an article from the publisher's website using "Zotero Connector", so I already obtained the metadata and PDF copy as a Zotero attachment. However, the corresponding item that synced to Notion indicates an empty "reading status" field, instead of "Ready".

**Comment by dvanoni** [comment]
Hi, @nonPointer. That's a great point!

I think the best way to achieve this is to change the `Reading Status` property from a **multi-select** property to a [**status** property](https://www.notion.so/help/guides/status-property-gives-clarity-on-tasks). A status property allows you to set one of the status options as the default. I just updated the advanced template to use this.

I'm hoping this will fit your needs. Let me know if it works for you!

**Comment by nonPointer** [comment]
> Hi, @nonPointer. That's a great point!
> 
> I think the best way to achieve this is to change the `Reading Status` property from a **multi-select** property to a [**status** property](https://www.notion.so/help/guides/status-property-gives-clarity-on-tasks). A status property allows you to set one of the status options as the default. I just updated the advanced template to use this.
> 
> I'm hoping this will fit your needs. Let me know if it works for you!

It works! Many thanks for your kind assistance.
