### ISSUE TITLE
Open notion pages via URL

### ISSUE THREAD

**Issue by bernicecheung** [dvanoni/notero#213]
Thanks for developing this wonderful tool! 

**Describe the issue**
I would like to open the notion URL on google chrome, so I selected it as the application when I clicked on the link and checked to remember this option (which clearly I should not have to do without testing it). However, the URL can't be opened through google chrome, nor could I find the option to restore the selection to open the URL on Notion desktop. Would you mind showing me how to reverse the application preference and change it back to Notion? Thanks! 

**Screenshots**
<img width="334" alt="image" src="https://user-images.githubusercontent.com/56136752/211950712-edec8de5-f19d-4e2e-b3a3-9ed5ed1a6c5c.png">

**Comment by dvanoni** [comment]
Hi, @bernicecheung! It sounds like your original goal might be captured in #53. Does that sound correct?

As for resetting the application preference, do you remember where exactly that prompt appeared?

- If it was in Chrome, I think you may be able to remove that setting by navigating to `chrome://settings/handlers`.
- I'm not sure which operating system you're using, but if it's Windows, you may be able to change this in [default apps](https://support.microsoft.com/en-us/windows/change-default-programs-in-windows-e5d82cad-17d1-c53b-3505-f10a32e1894d).
- If it's macOS, perhaps [something here](https://superuser.com/questions/1294654/how-to-remove-custom-url-handlers-in-os-x) will work for you.

**Comment by bernicecheung** [comment]
Thank you for the prompt response. Unfortunately, the preference setting was prompted by Zotero, and I couldn't find the place to reset the settings. Reinstalling Zotero also didn't restore the settings. However, I can still open the link through the web version of Zotero.

**Comment by dvanoni** [comment]
Darn. Well, hopefully I'll have a proper solution for you once #53 is in place.

Is it alright if we close this issue, and you can follow along with #53?

**Comment by bernicecheung** [comment]
Sure! I'll follow #53. Thank you!
