### ISSUE TITLE
Syncing journal name as a property

### ISSUE THREAD

**Issue by GitCats-061** [dvanoni/notero#214]
Hi, I find this Notero add-on very useful for my Ph.D. work. 
Thank you so much for creating it!

I'm just guessing that it would be even better if it extracts "Journal Name" of the items in a collection, just like it extracts author names, DOI and so on.

Would it be possible?
I'd be appreciate it if you consider about this.

Best regards,
Daisuke

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dvanoni** [comment]
Hi, @GitCats-061! I'm glad you're finding Notero useful!

It's definitely possible to sync journal, and some other folks have asked about it as well. It's on my todo list along with some related issues in [this milestone](https://github.com/dvanoni/notero/milestone/4).

**Comment by dvanoni** [comment]
Happy holidays! I've just released [v0.5.5](https://github.com/dvanoni/notero/releases/tag/v0.5.5) which adds support for syncing a **text** property named `Publication`—which I believe should be the equivalent of Journal.

I also want to add support for customizing the properties that can be synced. I'm tracking that work in #355, so please follow along there if you're interested!
