### ISSUE TITLE
Don't see new Collection property

### ISSUE THREAD

**Issue by austinmw** [dvanoni/notero#216]
**Describe the issue**
Hi, I'm using the latest version of Zotero, but I don't see the new collection property recently released in my Notion database. How can I get access to that?

**Comment by dvanoni** [comment]
Hi, @austinmw! You'll have to manually add a **multi-select** property named `Collections` to your Notion database. The property type and name must match that exactly for it to work (at least for now). Once that's in place, that property should populate whenever you perform a sync, but let me know if it doesn't.

**Comment by austinmw** [comment]
Worked, thanks!
