### ISSUE TITLE
APIResponseError: query failed

### ISSUE THREAD

**Issue by AyberkNardan** [dvanoni/notero#224]
Hi. I have been taking the API error query failed since I changed my computer SSD. At that time, I also upgraded my operating system to ubuntu 22.10. I don't know If the issue is relevant to them. Can you help me? 
Thanks!

![Screenshot from 2023-02-15 17-08-01](https://user-images.githubusercontent.com/26655436/219053222-c6679409-eda3-4fb2-8ec0-92cd4a630e24.png)

**Comment by dvanoni** [comment]
@AyberkNardan, it looks like you're encountering the same issue as #217. Please let me know if the solution there solves your issue.

**Comment by AyberkNardan** [comment]
Thanks. The solution solved my problem as well.
