### ISSUE TITLE
File path is not syncing

### ISSUE THREAD

**Issue by tpulha** [dvanoni/notero#225]
The file path used to sync to the Notion property "File". It is not doing so now, even though Notero was not updated. Not sure if Notion was. Both on latest version.

**Comment by dvanoni** [comment]
@tpulha, I see you wrote `File` as the property name. In order for the value to sync, it needs to be `File Path`. Can you confirm that the property in Notion has the full name?

**Comment by tpulha** [comment]
You're right! Created the property "File Path" and it's working again. Don't know what happened there.
