### ISSUE TITLE
Edit "Type" property to allow enter/ paragraphs or bullets in typing. 

### ISSUE THREAD

**Issue by ana-pasta** [dvanoni/notero#228]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm trying to type in notes about key findings relating to a paper- and it comes in as one big block of text that I can't use enter for. 

**Describe the solution you'd like**
Ability to add either a bullet pointed list of to use enter key as per a word processing tool, whetre you actually get to go to the next line (whether this is within the "type" property, or as a separate property, perhaps a "type list" property)

**Describe alternatives you've considered**
Currently using a dodgy workaround by making a list of bullets in word, copying it into Notion and typing from there- but it's clunky and doesn't always work smoothly.

**Comment by dvanoni** [comment]
Hi @ana-pasta, would you mind sharing a screenshot of where you're typing so I can better understand the issue? Thanks!

**Comment by ana-pasta** [comment]
<img width="828" alt="Screen Shot 2023-02-22 at 12 47 04 pm" src="https://user-images.githubusercontent.com/125881128/220611427-52aef4cf-15f8-4edd-9da7-fb813d04779d.png">
 Hi @dvanoni, here is a screenshot of what I'm trying to illustrate. Basically- I want to be able to write multiple paragraphs and have space between them to separate rather than flow on text.

**Comment by dvanoni** [comment]
Thanks for sharing those screenshots, @ana-pasta!

I believe this is all controlled by Notion, so I don't think there's anything I can do about it on my side. However, I believe you can use "shift+enter" to create a new line. Does that work for you?

**Comment by ana-pasta** [comment]
Brilliant, feels very obvious now that I've tried it but it does indeed work- thanks so much for your help! 😁
