### ISSUE TITLE
Notero Preferences MAC

### ISSUE THREAD

**Issue by mehreenmas** [dvanoni/notero#230]
Hi, the "property preferences" option is not showing up in Notero Preferences on MAC. Its showing on my windows laptop! Please let me know how to fix this. 
<img width="474" alt="Screen Shot 2023-02-26 at 6 37 57 PM" src="https://user-images.githubusercontent.com/63957623/221460554-648dbd4c-4ab5-446e-acac-a6e6306b4536.png">

**Comment by dvanoni** [comment]
Hi, @mehreenmas. That's strange! Do you have the latest version (0.4.6) installed on your Mac? That's the only thing I can immediately think of.

**Comment by mehreenmas** [comment]
Yup, I have the latest one! Let me try and reinstall it to see if it works.

**Comment by thomasXwang** [comment]
Hi @dvanoni , I've been encountering the same issue: the **Tools** → **Notero Preferences**... menu item has disappeared, since I have updated Zotero (it is currently on v6.0.22)
However, Notero still appears as Enabled under the **Add-ons Manager**

**Comment by mehreenmas** [comment]
I reinstalled the add-on and that seemed to fix the problem

**Comment by thomasXwang** [comment]
> I reinstalled the add-on and that seemed to fix the problem

Thank you, it did the trick for me too!

**Comment by dvanoni** [comment]
I'm glad you both were able to get it working!
