### ISSUE TITLE
How to find the collections property?

### ISSUE THREAD

**Issue by fredericky123** [dvanoni/notero#231]
I want to use the collection property to visualize the items in notion like in zotero, however, I used the template of advanced example, I coundn't find the property. Then how to add a view of items by collection property? Thanks a ton!

**Comment by dvanoni** [comment]
Hi, @fredericky123. I had not yet added the Collections property to the advanced example; sorry about that! I've just now added it if you want to copy the example again.

Alternatively, you can also add the property to an existing database. You'll just need to ensure that it's created as a **Multi-select** property and is named `Collections`.

**Comment by fredericky123** [comment]
Thanks a ton!
