### ISSUE TITLE
Syncing is exporting the wrong citation style? 

### ISSUE THREAD

**Issue by nirurin** [dvanoni/notero#238]
**Describe the issue**
I noticed all my citations (the long citations) were not using the Harvard citation style when I looked at the database in notion, but I also wasn't sure I ever set it properly in Zotero. So I went in and set it to cite-them-right Harvard 12th edition. If I export the bibliography now, it seems to export the correct citations. 

HOWEVER - I tried to re-sync the database to notion, and it didn't update the citations. Shame. Figured it just wasn't seeing the change, so I manually corrected every citation in notion. 

I then, just as a test, synced one single entry in zotero... and it reverted the notion database citation for that entry back to whatever citation style it was using before. 

**To Reproduce**
Do the above.

**Expected behavior**
The synced citation should be the one set in zotero preferences. 

**Screenshots**

![Screenshot 2023-03-16 054117](https://user-images.githubusercontent.com/3751273/225525339-7f24fe77-537a-4186-90ea-53035c0b7eb5.png)

**Comment by dvanoni** [comment]
Hi @nirurin, thanks for reaching out. I think you may just be on the wrong screen in the Zotero preferences. I see your screenshot is showing the **Cite** tab in the preferences. The setting that you need to change is **Item Format** on the **Export** tab. Is that set to the format you want?

![CleanShot 2023-03-16 at 21 01 49@2x](https://user-images.githubusercontent.com/299357/225809855-9feba9f6-a4a5-47e0-b8c3-11d7840c9b1b.png)
