### ISSUE TITLE
Unable to update literature to Notion

### ISSUE THREAD

**Issue by zny3108** [dvanoni/notero#239]
Thank you for your hard work on this add-on.
I suddenly encountered a problem these days.
When I was in zotero use, everything is normal, adding the new literature, have appeared in the synchronous Notero popup window, but when I returned to the Notion, found no update this literature.
Would you please take a look at this question? Thank you very much

**Comment by dvanoni** [comment]
Hi @zny3108, thanks for reaching out.

Does the Notero popup (see below screenshot) still show up? Does it show any error message, or does it show the green checkmark like in the screenshot?

![CleanShot 2023-03-16 at 20 43 27@2x](https://user-images.githubusercontent.com/299357/225807519-0465c7b2-bfa3-4ce7-b66b-fb668c48f141.png)

**Comment by zny3108** [comment]
Thank you for your reply.
These diagrams are all show up, and everything is fine in Zotero, and there were no errors reported. The only change is that there is no update in Notion.
I also double-checked if the Notion is updated to when I change folders in Zotero, which is also fine.
I'm at my wit's end now.

**Comment by dvanoni** [comment]
Hmm very strange! Let's try something... If you create a new database in Notion, connect it with Notero, and update the database ID in the Notero preferences, are you able to sync items into that new database?

**Comment by zny3108** [comment]
It Notero again, thank you very much for your advice.
Although the previous issues have not been fixed, but I can start taking notes again.
Finally, thank you again. Your answer and your work on this add-on have greatly improved my learning efficiency. 
Thank you.

**Comment by zny3108** [comment]
I've got some new cues for you.
1. It has embedded the address to jump to notion in zotero:
![image](https://user-images.githubusercontent.com/52792249/225819704-45176ba4-f9bd-405c-8dd1-9c9a58faf5a9.png)
2. I clicked on the address and found that it did appear on the correct page, namely that it was saved in Notion
![image](https://user-images.githubusercontent.com/52792249/225819892-5333ce05-85d4-4c3a-9967-821673962da4.png)
3. But when I go back to the bibliographic page, it's gone, it's not recorded here
![image](https://user-images.githubusercontent.com/52792249/225820325-739ca683-edb8-4beb-9a00-66a502dd21b4.png)
4. Strangely, I found it here, and when I clicked "move to", it was there.
![image](https://user-images.githubusercontent.com/52792249/225820369-7aa93218-6298-4822-8d95-8b1032914bc7.png)
5. But I don't see it in the superior menu("private")
![image](https://user-images.githubusercontent.com/52792249/225820523-b7be6d3d-b559-45cc-a723-28801e6309e6.png)
Do you have any new idea? Please tell me

**Comment by zny3108** [comment]
The possibility occurs to me that it is not a problem with the error reported, but rather that I cannot see the latest addition at the top of the template because of a sorting error in Notion? How do I reset the sort?

**Comment by zny3108** [comment]
Now I can confirm the problem: it is normal to import the literature, but the imported new literature is not at the top of the table of the template, so I did not find it at the beginning. 
Do you have a way to restore the sorting problem when importing new documents?

**Comment by dvanoni** [comment]
Hi @zny3108, thanks for the additional info!

Something you can try is to add two more properties to you Notion database. There are two special types of property called `Created time` and `Last edited time`. If you add those to your database, you can then use them to sort the pages in your database. For example, if you sort by `Last edited time` in **descending** order, then whenever you sync an item from Zotero into Notion, it will show up at the top of your database.

Can you let me know if that helps?

**Comment by zny3108** [comment]
Yes, you're right. 
Although I am not sure why this is the case, your answer solves my question. 
Thank you very much.
