### ISSUE TITLE
You have exceeded the maximum database property schema size, how to solve

### ISSUE THREAD

**Issue by fredericky123** [dvanoni/notero#250]
How to solve this
<img width="282" alt="image" src="https://user-images.githubusercontent.com/13982749/232205510-e7b5fc82-e002-4afd-9550-1548010e492c.png">

**Comment by dvanoni** [comment]
Hi @fredericky123, this is interesting. I don't think I've seen this error before.

Does the error occur with all items, or is it only specific items? If it's specific items, can you tell if there's something different about the ones that encounter the error? My best guess is that there's a field that's too long.

**Comment by fredericky123** [comment]
It occurs with all items

**Comment by dvanoni** [comment]
I thought this might have something to do with multi-select properties since the [Notion documentation](https://developers.notion.com/reference/request-limits#limits-for-property-values) states that they have a limit of 100 options. But, I ran a test by adding more than 100 tags to an item, and the error message is different:

> APIResponseError: body failed validation: body.properties.Tags.multi_select.length should be ≤ `100`, instead was `101`.

I'm going to try reaching out to Notion support because I don't know what the "maximum database property schema size" is referring to. I'll let you know what I hear from them.

**Comment by fredericky123** [comment]
Thanks a ton, @dvanoni ! I also searched "maximum database property schema size" and almost found nothing from the Internet.

**Comment by dvanoni** [comment]
Same! It seems you may have unlocked a new error! 😆

**Comment by dvanoni** [comment]
@fredericky123, can you do me a favor to help me debug this issue? Would you mind installing [this test build](https://nightly.link/dvanoni/notero/actions/runs/4728509773/notero-0.4.7-94.zip) that enables more logging and then send me a screenshot of the output in the error console when you try to sync an item? See the video below for an example. Thanks!

https://user-images.githubusercontent.com/299357/232671668-6a892763-ce41-4d6b-b5cd-6a406578b2a1.mp4

**Comment by fredericky123** [comment]
Thanks @dvanoni  It's amzing that using this test build will not casue bugs!!

**Comment by dvanoni** [comment]
@fredericky123, can you clarify—did you install the test build and you're no longer seeing the error?

If you're still seeing the error with this test build, it'd be great if you could send me a screenshot of the error console so I can see the details of the failing request.

Thanks!

**Comment by fredericky123** [comment]
After installing the test build, the bug disappreaed. If it happens again, I will let you know

**Comment by dvanoni** [comment]
Interesting. 🤔 Thanks for the update! Please do let me know if you see the error again.

**Comment by fredericky123** [comment]
No problem!

**Comment by sean-stark** [comment]
Hi there, Im facing the exact same issue, could you tell me how to install the test build?

**Comment by dvanoni** [comment]
Hi @sean-stark! If you're using the test build and encountering the issue, could you follow the video above to capture some log messages and then send me a screenshot of the logs? I'd greatly appreciate it!

**Comment by fredericky123** [comment]
I encountered the problem again:
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/13982749/233230029-5d626962-b342-4b75-a272-8dd8ad99256b.png">

**Comment by dvanoni** [comment]
@fredericky123, thank you! This is what I was looking for.

Could I trouble you for another screenshot just like this one, but can you click on the popup in the bottom right to dismiss it so we can see the full log message underneath it?

Also, are you alright with me sending this screenshot to the Notion team?

**Comment by fredericky123** [comment]
Of course you can send this screepshot to Notion to locate the problem
![CleanShot 2023-04-20 at 09 08 33@2x](https://user-images.githubusercontent.com/13982749/233231949-a9e691cd-0867-4d15-bac1-218d071856c2.png)

**Comment by dvanoni** [comment]
Excellent. Thank you!! I'll let you know what I hear back from the Notion team.

**Comment by dvanoni** [comment]
Hey @fredericky123, the Notion team is still looking in to the details, but they said it could be related to the number of multi-select options in the database. Are you able to tell me how many different options your database currently has for the `Collections` and `Tags` properties? Thanks!

**Comment by fredericky123** [comment]
> Hey @fredericky123, the Notion team is still looking in to the details, but they said it could be related to the number of multi-select options in the database. Are you able to tell me how many different options your database currently has for the `Collections` and `Tags` properties? Thanks!

I can't count exactly right now, but I do have a lot of `collections', around 100 or so

**Comment by dvanoni** [comment]
Hey @fredericky123, this is what I heard back from the Notion team:

> The limit in this case is for the overall size of the database schema, rather than for the number of options for a particular field. Having multiple fields with select and multi-select options, and many different options, would lead to this limit.
>
> If you're encountering this error, it most likely means that many unique values are being sent to Select and Multi-Select properties in the database in question. I'd recommend switching these to richText fields, if you're submitting many different options and don't need users to pick from a smaller list of defined options.

They didn't say exactly what the limits are, so I'll probably try to get more clarity around that from them.

Would you mind sharing how many **select** and **multi-select** properties you have in your database and roughly how many options are in each? Thanks!

**Comment by fredericky123** [comment]
Thanks @dvanoni !
I have only one field with multi-select options, that is "Collections". Indeed, I used exactly your template of database structure.

**Comment by dvanoni** [comment]
If you used one of the templates, do you also have the `Item Type` and `Tags` properties? In the templates, `Item Type` is a **select** property and `Tags` is a **multi-select** property. If you have those properties, can you tell me how many options are in those?

Ultimately, I'm trying to determine what a typical number of options would be for these properties (including `Collections`) for a user like yourself. And then I'd want to see how close these numbers are to the Notion limits so I can determine what adjustments may need to be made.

**Comment by fredericky123** [comment]
Oh yes, I have Item Type, there are only several options.
There is too many options for Tags in my database, as you can see from the picture. Zotero usually generate tags automatically, maybe we need to swith this field to richText fields.
<img width="631" alt="image" src="https://user-images.githubusercontent.com/13982749/235062836-3161c1af-a739-4e32-a3d5-cb1a6d8771d2.png">
<img width="462" alt="image" src="https://user-images.githubusercontent.com/13982749/235063231-37ee827e-d8f1-4c38-a014-827171d0bccf.png">

**Comment by dvanoni** [comment]
Thanks for that info! Yeah, I think you're right about the `Tags` options being too numerous.

I think this relates to #255. Maybe an approach could be to sync user-defined as multi-select options but then sync automatic tags (if desired) as rich text.

The only potential workarounds I can think of for your current issue are:

- disable/delete the automatic tags in Zotero and remove them from Notion
- remove the `Tags` property from Notion altogether

**Comment by fredericky123** [comment]
Thanks @dvanoni ! Actually, I never used information from automatic tags but I do used customized tags. If we can split the tags to two parts, that would be great!

**Comment by fredericky123** [comment]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/13982749/235068471-4e22c0ef-a733-40a8-96fb-8e8b0b374a90.png">
I can delete the automated tags in one click, let me delete them and check whther this issue is solved.

**Comment by fredericky123** [comment]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/13982749/235068471-4e22c0ef-a733-40a8-96fb-8e8b0b374a90.png">
I can delete the automated tags in one click, let me delete them and check whther this issue is solved.

**Comment by fredericky123** [comment]
> The only potential workarounds I can think of for your current issue are:
> 
> * disable/delete the automatic tags in Zotero and remove them from Notion
> * remove the `Tags` property from Notion altogether

This works!
