### ISSUE TITLE
Sync Citation Key with Zotero for Enhanced Workflow

### ISSUE THREAD

**Issue by Fabioni** [dvanoni/notero#254]
Hi there, I appreciate your fantastic and useful plugin. My workflow, in conjunction with Overleaf, would significantly benefit if Notion could display the Citation Key from Zotero directly. I believe this enhancement is critical for an efficient workflow and warrants its own issue. However, if you disagree, please feel free to remove it.

              Would be nice to have the Citation Key synced when detected

_Originally posted by @patrickmesana in https://github.com/dvanoni/notero/issues/49#issuecomment-1436110345_

**Comment by dvanoni** [comment]
This feature has been released in [v0.5.1](https://github.com/dvanoni/notero/releases/tag/v0.5.1)! 🎉
