### ISSUE TITLE
Notero not syncing deletions

### ISSUE THREAD

**Issue by KenupCF** [dvanoni/notero#259]
I don't know if this is expected behaviour or not, but when I delete an entry from my Zotero library, it does not sync up to a deletion in Notion. I am using Zotero 6.0.2.6 on Windows 10 Home.

Since it is not an error per se, I don't have a log to share, sorry!

**Comment by dvanoni** [comment]
Hi @KenupCF, thanks for reaching out! This behavior is expected, but not desired. 😅

Some other folks have discussed this same thing in #46. See that issue for ideas about how we might solve this in the future, and a potential temporary workaround.

I'm going to close this issue as a duplicate of #46, but please feel chime in on that one and give it a 👍.
