### ISSUE TITLE
Sync of zotero to notion not happening automatically anymore.

### ISSUE THREAD

**Issue by GasserElmissiery** [dvanoni/notero#268]
Firstly, I would like to thank you for this plugin, It has been tremendously helpful!

I was using your plugin a few months ago and it worked perfectly but now I started using it again and for some reason whenever I add an item in my zotero sync folder it does not prompt the usual bottom-right notion notifcation saying "saving item to notion". 
I tried to force sync the items by clicking on the top right green sync button "sync with zotero.org" and still nothing happens after it "syncs" (even says last synced 1 second ago).

HOWEVER, If I right click on the item in zotero, I see in the menu an option to "sync to notion" and then it works! I guess this means that there is no issue between the connection of zotero and notion and that the issue is that adding an new item to the folder no longer prompts an automatic sync. I made sure to reinstall the plugin and that it is the latest version and yet the issue persists.

**Comment by dvanoni** [comment]
Hi @GasserElmissiery, thanks for reaching out!

I'm not sure if the "Sync with zotero.org" button will cause the items to sync to Notion. The plugin is designed to sync only when new items are added to your monitored collections (folders) or if those items are modified.

It's good to hear that the "Sync to Notion" option in the right-click menu is working.

Can you confirm that the collection you're adding new items into is enabled for syncing? If you open Notero Preferences from the Tools menu, there should be a green checkmark next to the collection that you want to be syncing. If it's not enabled, you should be able to enable it by double-clicking on the row.

![CleanShot 2023-05-15 at 19 12 45@2x](https://github.com/dvanoni/notero/assets/299357/7811fdce-cb09-406a-8f2c-3e68c082c953)
