### ISSUE TITLE
Items of type conference paper are not added to Notion database

### ISSUE THREAD

**Issue by kanz76** [dvanoni/notero#269]
Hi Dvanoni,

First of all, thanks for this great tool. 

There seems to be an issue synchronizing items of the type "conference paper" to the notion database. I have to manually add the notion tag for it to work. Journal paper type, on the contrary, works just fine.

**Comment by dvanoni** [comment]
Hi @kanz76, thanks for reaching out!

Can you share more details about the cases in which the conference paper items do and do not sync? If you modify a conference paper item in some other way (i.e. not adding the `notion` tag), does that trigger a sync?

Also, are all of the items in question in one of your monitored collections (the ones you've enabled sync for in Notero Preferences)?

**Comment by kanz76** [comment]
Here's an example of a conference paper https://openreview.net/forum?id=YWNAX0caEjI

When I add it to my collection (using the Zotero connector Chrome extension), the notion tag is not attached to it, and, therefore, does get added to my Notion database. 

However, the following 2 workarounds seem to trigger a sync. 

1) Manually adding the notion tag triggers a sync with my Notion database. 
2) Changing the item type from Conference paper to, say, Journal paper, automatically adds the notion tag, which triggers a sync. 


And yes, all the items in question are in my monitor collection.

**Comment by dvanoni** [comment]
I just tried saving that paper to my Zotero library using the connector, and it successfully synced to Notion. 🤔 

I wonder if there's another Zotero plugin that's somehow conflicting with Notero. Would you mind sharing the plugins you have installed in Zotero? If you try disabling the rest of them, does that have any impact?

Also, would you mind capturing a screenshot of the Zotero logs by opening the **Error Console** from the **Tools > Developer** menu? If you open the Error Console first, click the **Clear** button at the top, and then import a paper using the connector, we should hopefully be able to get some insight as to what's happening.

**Comment by kanz76** [comment]
I got a fresh install of Zotero today. Here are the pluggings

<img width="778" alt="Screenshot 2023-05-17 215959" src="https://github.com/dvanoni/notero/assets/26411926/fc9c20b1-cacf-43db-8932-39997a24f3c5">

Here's the Console log when I add a paper using zotero connector 

<img width="303" alt="Screenshot 2023-05-17 220417" src="https://github.com/dvanoni/notero/assets/26411926/ff2a2cba-4084-46c9-beda-690d654e7742">

**Comment by dvanoni** [comment]
Hmm interesting. Is Zotero downloading the PDF of the paper for you? It's downloading it for me, so I see two messages with `add item` (one for the item and one for the PDF attachment). But even if it wasn't downloading the PDF, I would still expect the first `add item` to end up triggering a sync.

When you import a journal paper, does Zotero download the PDF?

For reference, here's what I see on my side. I've annotated the log lines with what they mean.

![CleanShot 2023-05-17 at 20 27 47@2x](https://github.com/dvanoni/notero/assets/299357/68361be4-0279-4a9e-bcb5-67bfbc824e19)

I'm a bit stumped on this one. I'm not sure what's preventing the usual sync process from happening for just this one type of item...

**Comment by kanz76** [comment]
No, I'm not downloading PDFs, I download PDFs later on my computer when I am about to read.

For instance, with the link I shared with you (https://openreview.net/forum?id=YWNAX0caEjI), I'm saving to zotero connector the very page on which I'm landing, without further clicking on the PDF icon next to the paper title. 

So I am doing this 
<img width="763" alt="image" src="https://github.com/dvanoni/notero/assets/26411926/a0f31605-f28d-44c7-9aa8-f2f22154cb7f">

Instead of this 
<img width="632" alt="image" src="https://github.com/dvanoni/notero/assets/26411926/08cc0092-5e78-437c-be12-cd82ff2e4e50">


The reason why I am doing this is because the PDF approach does not have complete metadata to generate accurate citations. 

That said, the PDF approach triggers a synch and gets saved to my Notion database because it is automatically saved as a Journal paper, instead of a Conference paper.

**Comment by dvanoni** [comment]
Thanks for that additional information! I was able to reproduce the issue by disabling the "Automatically attach associated PDFs and other files when saving items" option in the Zotero preferences.

I'll dig into this further and see if I can determine what's preventing the sync from occurring. In the meantime, you should be able to manually trigger the sync by right-clicking on either an item or a collection and selecting the "Sync to Notion" option.

**Comment by dvanoni** [comment]
Hi @kanz76, I finally got around to digging into this, and I just released a fix in the latest version (0.5.13). Check out PR #453 if you're interested in the details.

Thanks again for reporting this issue!
