### ISSUE TITLE
No sync option in collection or item context menus

### ISSUE THREAD

**Issue by Clfh47** [dvanoni/notero#270]
Ubuntu 22.04
Notero 0.3.5
Zotero 6.0.26
LibreOffice plug-in used
Chrome -> Zotero browser connector used

Individual items sync to Notion when added to a collection (as expected), but I have a large number of items already in Notero from before I discovered Notion + notero. 

I want these, too, to be synced into Notion.

Neither of the (right-click) context menus (for collection or for item) has a 'Sync ... to Notion'  option.

Is this a notero bug, or have I missed a configuration detail somewhere?

I know about the work-around of copying items into a different collection, but would rather do it 'properly' if possible.
I've also found that making a (trivial) amendment to the Info of an existing item causes it to be synced to Notion.

*[Fantastic integration, by the way. Many thanks!]*

TIA

**Comment by dvanoni** [comment]
Hi @Clfh47!

It looks like you're on Notero version 0.3.5. The sync option was added to the context menus in version 0.4.4, so I believe you may just need to update to the latest version.

Let me know if that works!
