### ISSUE TITLE
Items not syncing after last update to Notero 0.4.6

### ISSUE THREAD

**Issue by MelanieN** [dvanoni/notero#275]
**Describe the issue**
Items not syncing to notion after last update to Notero 0.4.6 (May 17th)

**To Reproduce**
MacOS 13.3.1
Notion 2.1.15
Zotero 6.0.26
Notero 0.4.6

**Expected behavior**
Allow to sync folders to Notion

**Comment by dvanoni** [comment]
Hi @MelanieN, thanks for reporting an issue!

Is it just the automatic syncing that has stopped working, or does manual syncing also not work? If you right-click either a collection or an item and select "Sync to Notion," does an error message appear?

**Comment by dvanoni** [comment]
Hmm I wonder if there's a bug with the upgrade process. I'm glad you were able to get it working! Are you good with closing this issue?

**Comment by buchuitoudegou** [comment]
> Somehow, there was no option anymore to sync folders to Notion, I noticed a friend had the same problem, but I've added the xpi file again to the add-on manager and now it seems to work again.

Same issue here. I tried turning it off and on again and it worked. But after I closed Zotero and opened it again, the plugin seemed to stop working again. Neither the automatic synchronization nor the manual one in the right-click pannel worked.

And I also tried both of the `0.4.5` and the `0.4.6` versions. Seemingly they have the same problem.

<img width="257" alt="image" src="https://github.com/dvanoni/notero/assets/25972139/b62ce227-240a-4461-b450-67a863beeb3d">

**Comment by dvanoni** [comment]
Hi @buchuitoudegou, thanks for the additional input. It looks like you're on a Mac—is that correct? If so, I think you might be encountering issue #90. Does that sound like it describes what you're experiencing?

**Comment by buchuitoudegou** [comment]
Yes! But it seems this issue hasn't been fixed yet?

Anyway, thanks a lot for providing such an amazing plugin!

**Comment by dvanoni** [comment]
Correct, #90 is still an open issue. It turns out it's a bit complicated to fix. 😅

I'll close this issue for now. Thanks for the input, y'all!
