### ISSUE TITLE
Replace DTD with Fluent in Zotero 7 preference pane

### ISSUE THREAD

**Issue by dvanoni** [dvanoni/notero#281]
For Zotero 7 preference panes, we're currently using the `extraDTD` property to provide localization strings. This functionality is [being removed](https://groups.google.com/g/zotero-dev/c/M_86IbuT8Nc) in favor of Fluent, so we'll need to update accordingly before releasing for Zotero 7.

https://github.com/dvanoni/notero/blob/9f74de3fd1131b5149e587eff069221c553262a2/src/content/services/preference-pane-manager.ts#L10

**Comment by sheldon123z** [comment]
kindly ask when the release will be ready for zotero 7 beta? the new versio of zotero is smooth as good...

**Comment by dvanoni** [comment]
Up until the latest beta version of Zotero 7 which removed the old localization support, Notero was actually already working pretty well with Zotero 7 based on the work that I'd previously done. Unfortunately, with this latest change in Zotero 7, the preferences pane for Notero currently doesn't work, so I'll need to fix this before it'll be usable in Zotero 7 again.

I'm not sure about the timeline right now, but I'll be sure to update this issue when I have a fix in place.

**Comment by dvanoni** [comment]
Hi @sheldon123z, I just released [version 0.4.9](https://github.com/dvanoni/notero/releases/tag/v0.4.9) that includes this fix. Notero should be working in Zotero 7 now! Please give it a try and let me know if you run into any issues.
