### ISSUE TITLE
Can connected with multi database?

### ISSUE THREAD

**Issue by ccwanggl** [dvanoni/notero#287]
Hi, notero is a great zotero plugin, i wonder if it can connected with multi database. usually i need to tracking multi research feild, i wan't mixed those info together.

**Comment by dvanoni** [comment]
Hi @ccwanggl! I do hope to add support for multiple databases in the future. Please follow along with #119 for progress updates and a possible temporary workaround.

**Comment by dvanoni** [comment]
Duplicate of #119
