### ISSUE TITLE
[Question] How to safely and efficiently remove link attachments created by Notero?

### ISSUE THREAD

**Issue by nonPointer** [dvanoni/notero#288]
For some reasons, I am no longer use Notion anymore and wanna get rid of attachments which all named "Notion" in Zotero.

**Comment by dvanoni** [comment]
Hi @nonPointer, I believe you can achieve this by using a saved search in Zotero to find all of the items named "Notion," select them all, and then delete them.

Please let me know if these steps work for you!

1. Open the **Advanced Search** window.
2. Enter the following search criteria:
   - `Title` `is` `Notion`
   - `Item Type` `is` `Attachment`
3. Click **Search** to ensure the expected results appear.
4. Click **Save Search**, and name the saved search whatever you'd like.
5. Select the saved search in the collection menu (left sidebar) if it's not already selected.
6. Select one of the Notion attachments in the main listing of items.
7. Select all items by pressing `Ctrl + A` on your keyboard (`Cmd + A` on Mac).
8. Delete all selected items by pressing `Backspace` on your keyboard.

https://github.com/dvanoni/notero/assets/299357/8ca900cb-7445-4fa8-bac4-b2320a1408d0

**Comment by nonPointer** [comment]
> Hi @nonPointer, I believe you can achieve this by using a saved search in Zotero to find all of the items named "Notion," select them all, and then delete them.
> 
> Please let me know if these steps work for you!
> 
> 1. Open the **Advanced Search** window.
> 2. Enter the following search criteria:
>    
>    * `Title` `is` `Notion`
>    * `Item Type` `is` `Attachment`
> 3. Click **Search** to ensure the expected results appear.
> 4. Click **Save Search**, and name the saved search whatever you'd like.
> 5. Select the saved search in the collection menu (left sidebar) if it's not already selected.
> 6. Select one of the Notion attachments in the main listing of items.
> 7. Select all items by pressing `Ctrl + A` on your keyboard (`Cmd + A` on Mac).
> 8. Delete all selected items by pressing `Backspace` on your keyboard.
> 
>  CleanShot.2023-07-08.at.22.28.29-converted.4.mp4

Thanks to Dvanoni! The problem has been solved by following the instructions.
