### ISSUE TITLE
"Sync to notion" not work in the zotero 7

### ISSUE THREAD

**Issue by ccwanggl** [dvanoni/notero#289]
As title

**Comment by dvanoni** [comment]
Hi @ccwanggl, I'm still working on support for Zotero 7.

Can you give me more details about exactly what's not working? When you click "Sync to Notion" does it not do anything, or do you see an error message?

**Comment by ChaolinTian** [comment]
Hi @dvanoni, I met this problem too, I click "Sync to Notion" in Zotero, it shows successful . as screenshot followed, but I didn't  find it in my Notion.  In a few days ago, it was working.  I don't know why this happen. My Zotero version is 6.0.26. 
![57d21009bf5d3e6f6595a3b21300f1c](https://github.com/dvanoni/notero/assets/70430088/800b71e3-5d70-477d-a64d-9761a5b37fbe)

**Comment by ccwanggl** [comment]
sorry for delay reply.
It does not do anything, no any message come out

**Comment by dvanoni** [comment]
Thanks, @ccwanggl. I'll look into this as I work on support for Zotero 7.

In the meantime, if you do need to use Notero, please continue to use Zotero 6 for now. I'll post an update here when I release a new version of Notero that supports Zotero 7.
