### ISSUE TITLE
APIResponseError: invalid request URL

### ISSUE THREAD

**Issue by BeckyYhui** [dvanoni/notero#292]
Nice tool! thank you so much! I am having an API Response Error: invalid request URL. I have attached a screenshot. Thanks in advance!
<img width="255" alt="image" src="https://github.com/dvanoni/notero/assets/130902598/5e65e0a1-6ae1-4b39-81ae-dd27b22ec2c1">

**Comment by dvanoni** [comment]
Hi @BeckyYhui, thanks for the kind words. 🙂 

This error usually occurs when there's something amiss with the database ID entered in the Notero preferences. Can you double check that the database ID follows the format described in the [Configure Notion](https://github.com/dvanoni/notero#configure-notion) section of the readme? It should be 32 characters consisting of only numbers and letters.

See #193 for an example of someone who had a similar issue.

Let me know if that helps!

**Comment by BeckyYhui** [comment]
Thank you very much. It's solved, sorry to bother you with this silly problem.
