### ISSUE TITLE
Zotero.Styles.get(...) getCiteProc is not a function

### ISSUE THREAD

**Issue by jrobbl** [dvanoni/notero#295]
I followed this tutorial
https://www.redgregory.com/notion/2022/10/14/how-to-connect-zotero-to-notion-with-notero

But Zotero doesn't add the item to Notion and shows the message
Zotero.Styles.get(...) getCiteProc is not a function

Any ideas?

**Comment by dvanoni** [comment]
Similar issues have been reported previously in #12 and #258. I believe the primary solutions in those were:

- Ensuring the `American Psychological Association 7th edition` style was installed (https://www.zotero.org/styles/apa)
- Ensuring an item format is selected on the Export tab of the Zotero preferences

@jrobbl, would you mind checking the above and let me know if there's anything there that helps?
