### ISSUE TITLE
Annotation in the papercannot be synchronized to my database

### ISSUE THREAD

**Issue by positivist1** [dvanoni/notero#296]
When I sync the annotated notes to notion, it already shows that the synchronization is successful, but there is no content in my database, the key is that the relevant notes or notes I have added tags such as Relevance or Problem or Purpose (note: paper is fine)

**Comment by dvanoni** [comment]
Hi @positivist1, I actually _just_ released initial support for syncing notes/annotations. (See #4)

Would you mind following the usage instructions in the [release notes for v0.4.8](https://github.com/dvanoni/notero/releases/tag/v0.4.8) and letting me know if you're able to sync annotations to Notion?

**Comment by MilkGe** [comment]
Hi @dvanoni ，now I can sync annotation to notion. Thank you very much!!

**Comment by positivist1** [comment]
Hi @dvanoni ，now I can sync annotation to notion. Thank you very much!!

**Comment by dvanoni** [comment]
Great! @positivist1, are you good with closing this issue?

**Comment by positivist1** [comment]
yes@dvanoni
