### ISSUE TITLE
Sync collection property to Notion database

### ISSUE THREAD

**Issue by dvanoni** [dvanoni/notero#30]
_Originally posted by @panyuz in https://github.com/dvanoni/notero/issues/6#issuecomment-1006216755_

> If it is possible to sync multiple folders to notion, would it be possible to add a field in notion to label the source of the entries? such as "Collection"?

Also [mentioned by someone in the Zotero Forums](https://forums.zotero.org/discussion/comment/393439/#Comment_393439).

**Comment by dvanoni** [comment]
Thinking through this, I believe using a **Multi-select** property for `Collection` is going to work best.

For example, consider the following setup:

<img src="https://user-images.githubusercontent.com/299357/149458959-f3fafd81-031b-4ff7-b76c-9402a5f13e09.png" alt="Collection sync example" width="396" />

Say we have both the `Paper A` and `Paper B` collections configured to sync to the same Notion database and "include subcollections" is enabled. We could have items that exist in multiple subcollections, and we'd want to reflect that when the item is synced to Notion. A **Multi-select** property seems like the best way to achieve that.

Additionally, it would be ideal for this to be robust to moving or renaming collections, and we should be able to achieve that by correlating Zotero collection IDs with Notion multi-select option IDs.

**Comment by 22-modifier** [comment]
I was wondering if you didn't need the file path. Instead, each collection and sub-collection have their own multi-select values. e.g. Plan A | Plan B | Lit Review | Methods. I would imagine that people doing a lit review would organize it by subtopics, so there would be additional subcollections (e.g. Historical context, Present state, Future opportunities). With Notion's Filter / Group Filter functionalities and Group By functionalities for Databases, users could recreate their Collection structure as they see fit. 

With that methodology, you might also be able to avoid different user opinions related to "Show Items from Subcollections" because the Notion filters could be set to "contains" or "does not contain" subcollection. 

Thank you again!

**Comment by dvanoni** [comment]
@22-modifier, thanks for the feedback! Could you help me understand your proposal a bit better? I'm a little fuzzy on how it would work.

For example, say I have these two Zotero items:
- `Item A` in the `Paper A ▸ Lit Review` subcollection (and only that subcollection)
- `Item B` in the `Paper B ▸ Lit Review` subcollection (and only that subcollection)

Given these two items, are you proposing to assign them multi-select option as follows?

<img width="357" alt="CleanShot 2022-01-22 at 17 13 43@2x" src="https://user-images.githubusercontent.com/299357/150659629-24419769-758b-464f-9469-6f4ed79ab481.png">

So then if I want to view only items from the `Paper A ▸ Lit Review` collection, I would use a filter like this?

<img width="486" alt="CleanShot 2022-01-22 at 17 15 50@2x" src="https://user-images.githubusercontent.com/299357/150659669-0317e970-54ea-4df6-a6ff-6262387a55d5.png">

Let me know if this is what you're thinking, or if I missed the mark.

I had considered an approach like this initially because it gives you an easy way to filter for all items within a higher-level collection—e.g., in this case `Paper A`—or items within similar subcollections like the two different `Lit Review` ones here.

However, after thinking through the implementation a bit, I realized that the "file path" solution might be necessary. The primary reason for this is that we need a one-to-one mapping between Zotero collections and Notion multi-select options so that, if a collection is renamed in Zotero, we have a way to properly update the corresponding option in Notion and keep things in sync.

Let me know what your thoughts are. Again, I really appreciate the feedback!

**Comment by 22-modifier** [comment]
@dvanoni How you have it in the above screenshots is exactly what I was referring to. I completely understand if their are hurdles that would prevent this implementation... I think users can adapt how they name their Collections if need be; and notion filters could still work on the more file-path-esque Collection names.

Frankly I have no coding experience or knowledge of how the databases are organized on the backend for either Zotero or Notion. If it's possible to just have an error message for duplicate Collection names, that might also circumvent the issue by keeping collection names unique with 1-to-1 relationships between apps. 

My personal use case for surgical journal articles mean I use hierarchical Collection names and would never have to worry about duplicate Collection names e.g.
-Upper Extremity
  > Hand
  > Wrist
  > Forearm & Elbow
  > Nerves
  > Soft tissue reconstruction

I think if you went with whatever is the simplest implementation, people would still get a lot of functionality out of it!

**Comment by adzcai** [comment]
Has there been any updates on this? I'd be interested in helping out!

**Comment by dvanoni** [comment]
Hi @adzcai! I started some initial exploration on this a few months ago, but I haven't had time to dig into it again.

If you'd like to try working on it, I'd be interested to see what you come up with! I pushed up my exploration to the `sync-collections-property` branch if you want to take a look at that.

Let me know if you want to discuss it at all!

**Comment by fredericky123** [comment]
HI @dvanoni , I think the template may inspire you some thinking to solve the collection property 
https://junhaoxyz.notion.site/10cf6d3c9f244e33ab5d7f5610d0a236?p=ff66d9a12a25487f92b88f23740fc273

https://www.youtube.com/watch?v=d6zRCPeN6b8

**Comment by KaorinaXu** [comment]
Hi @dvanoni , thanks for sharing, but can the Collection property be stuomatically recognized from zotero? Or I have to manually add multiple tags in Notion in order to seperate them into diffrerent views?

**Comment by dvanoni** [comment]
Hi @KaorinaXu, unfortunately I haven't had time to work on this yet, so the collection property is not available. Using tags is probably the next best workaround for now, even though it can be a bit tedious.

**Comment by KaorinaXu** [comment]
Thank you @dvanoni anyway! I'll try to explore more^_^

**Comment by feeds** [comment]
I found a quick hack which allows me to create views of different collections for my specific setup, and thought I'd post it in case it is interesting to other people here.

I am using Zotfile and save the pdfs locally on my computer. It is configured it such that the file path contains the collection name (e.g. `zoterolocation/collectionA/collectionB/paper.pdf`).

Since the filepath property is synced with notion, I can just create collection views by filtering based on the collection name contained in the filepath.
Of course this only works if every item is in only one collection, but this is ok for my purposes :)

**Comment by dvanoni** [comment]
@feeds, that's a clever solution! Thanks for sharing!

**Comment by josh-ashkinaze** [comment]
Any chance you can add this feature? I think the minimal way to do it is just as a string "machine_learning/neural_networks/foundational_work" etc

**Comment by dvanoni** [comment]
Happy holidays, everyone! 🌟 

I'm excited to share that this feature has finally been released in [version 0.4.3](https://github.com/dvanoni/notero/releases/tag/v0.4.3)! Give it a try, and let me know what you think!
