### ISSUE TITLE
Reconnect Notero with Notion 

### ISSUE THREAD

**Issue by EdwinHirtreiter** [dvanoni/notero#302]
Hi there,

as a result of a system failure of my notebook, I had to format my hard drive where my zotero literature database was located. Now my question is if there is a way that when I add the literature again to Zotero, the correct connection to the respective elements in the still existing notion database will be restored? From my perspective, I'd need to edit the link attachments, which notero automatically creates and link them to the already existing elements in the notion database.

I really appreciate any help you can provide!

**Comment by dvanoni** [comment]
Hi @EdwinHirtreiter, I'm sorry to hear about that! It sounds frustrating. 😞 

I believe it should be possible to reconnect your Zotero items to Notion, and I think you already have the right idea with editing the link attachments. I don't think Zotero allows you to edit the URLs of the attachments directly, so if you already recreated the link attachments, you'll have to delete those and create new ones using URLs from your existing Notion database.

Someone encountered a similar situation in #134, and in that discussion I shared a video showing how you can manually create the link attachments with the URL required to get Notero working again. Could you review the discussion there and let me know if those steps are able to get things working for you?

On a separate note, I'd also recommend creating a Zotero account and setting up [syncing](https://www.zotero.org/support/sync) if you're able to. This would sync your Zotero library—including Notero's link attachments—to your Zotero account and allow you to restore all the link attachments if you ever run into a similar situation in the future.

**Comment by EdwinHirtreiter** [comment]
Hi @dvanoni, thanks for your comprehensive answer! I've tried your suggestion and it works as long as I have the notero sync disabled. When I enable syncing duplicate entries show up in my notion database. Maybe I'll take the workaround and sync new entries manually (and keep automatic syncing disabled). 

Regarding your separate note: After this experience I'll try the zotero sync, instead of just backuping the pdf files.

**Comment by dvanoni** [comment]
Hi @EdwinHirtreiter, I just tested the process again myself, and I'm also getting duplicates.

I think I found the issue. It appears that when you copy a link to a page in the latest version of Notion, it's including an extra value at the end of the URL. I'm seeing `?pvs=4` appended at the end of the URL. Are you seeing that as well?

I think I can implement a fix for this in Notero, but until I have that in place, I believe you can work around this yourself by deleting that value when you paste it into Zotero. Please let me know if this resolves the duplication issue for you!

https://github.com/dvanoni/notero/assets/299357/97fd80e9-8bbc-4a95-bf5b-99536244caa0

**Comment by EdwinHirtreiter** [comment]
Thanks a lot, that works! I appreciate your immediate help!
