### ISSUE TITLE
Notero 0.4.10 does not work on MacOS

### ISSUE THREAD

**Issue by wadieskaf** [dvanoni/notero#314]
The new update for Notero which is v0.4.10 does not work on MacOS. 

When I updated it, the Notero Preferences under 'Tools' disappeared and it stopped syncing.

My system: 
Apple MBPro M2 Max
MacOS Ventura 13.5 with Zotero 6.0.26
 

_Note: everything was fixed when I rolled back to v0.4.9 and I am submitting this issue just to flag it for consideration._

**Comment by zbirobin** [comment]
I have the same issue on Windows.

**Comment by musjorben** [comment]
I have the same issue on Windows

**Comment by Libaniusrhetor** [comment]
I am having the same issue, Mac OS Ventura 13.4.1, Zotero 6.0.26

**Comment by meyoo88** [comment]
Same for me. Please fix this!!

**Comment by jankaWIS** [comment]
Same here, Mac OS Ventura 13.4.1, Zotero 6.0.26

**Comment by dvanoni** [comment]
Hi y'all, sorry about this! Thanks for reporting it.

My latest upgrade of dependencies introduced a change that ended up crashing Notero as it started up. (See #317 if you're curious.)

This should be fixed in version [0.4.11](https://github.com/dvanoni/notero/releases/tag/v0.4.11).
