### ISSUE TITLE
Add an icon for notero

### ISSUE THREAD

**Issue by llity** [dvanoni/notero#321]
There need an icon for notero.

**Comment by dvanoni** [comment]
@llity, I'd love for Notero to have an icon. I tried making one a while ago, but I'm not great at design and didn't come up with anything I liked. Maybe I'll try again some day...

Do you know anyone who would like to make an icon?

**Comment by llity** [comment]
May you can use the free icon on the web?
https://www.google.com/search?q=n+icon
![image](https://github.com/dvanoni/notero/assets/11771112/7b867279-bc89-43b1-925d-89c442146321)

**Comment by dvanoni** [comment]
Here's the icon I created with the help of AI. 😄 

<img width="256" alt="notero@2x" src="https://github.com/dvanoni/notero/assets/299357/ce7d2932-25f1-4a74-9fb1-43e0f7326c15">
