### ISSUE TITLE
Make database not full width / allow toggling full width

### ISSUE THREAD

**Issue by danjenson** [dvanoni/notero#329]
I have a widescreen monitor and it seems that I can't get the template to center the table, even when I have very few columns. This leads to a pretty inconvenient view:
![image](https://github.com/dvanoni/notero/assets/4793438/0affd609-c490-459b-8d98-a2f536ba7ffb)

I would like to be able to center the table, similar to other databases/tables I have.

**Comment by dvanoni** [comment]
Hi @danjenson, thanks for reaching out. Notero doesn't have any control over this aspect of your Notion database.

As far as I know, Notion always displays a _full-page_ database using the full width of your screen. If you'd like to display the database in a narrow view, I believe you'll need to embed it into another page as an _in-line_ database. See the [Full page vs. in-line databases](https://www.notion.so/help/intro-to-databases#full-page-vs.-in-line-databases) section of the Notion docs for more info.

Please let me know if this helps!

**Comment by danjenson** [comment]
Thank you -- I had to nest it inside another page!
