### ISSUE TITLE
Collection AutoSync list not showed on Windows 11

### ISSUE THREAD

**Issue by CossonArthur** [dvanoni/notero#331]
**Describe the issue**
After a clean installation of Notero, everything is working well, but in the Zotero desktop App on Windows 11 in the settings the list of all the collections which can be synced. 
The test has been made with the same installation and version on Windows 10 and the list is shown.

**To Reproduce**
Windows 11
Notero : 0.4.11
Zotero : 5.0.96.3

**Expected behavior**
The list to select the collection must appear.

**Comment by dvanoni** [comment]
Hi @CossonArthur, thanks for reporting this issue.

I see that you're on version 5.0.96.3 of Zotero which is now [over two years old](https://www.zotero.org/support/5.0_changelog). Notero hasn't been tested on Zotero 5 in a while, and I think the collections list specifically is using some functionality that's only available in Zotero 6 and up.

Are you able to update to the latest version of Zotero (6.0.27) and see if Notero works as expected with that?

**Comment by CossonArthur** [comment]
Updating Zotero, solve the issue !

Might be a change in the architecture
