### ISSUE TITLE
API Response Error: text is expected to be rich_text

### ISSUE THREAD

**Issue by ESCirit** [dvanoni/notero#338]
Hello,

I just started using both Notion and notero. 
I am having an API Response Error: title is expected to be rich_text. How can I fix this error?

Thanks in advance.

**Comment by dvanoni** [comment]
Hi @ESCirit, were you able to figure out the issue?

**Comment by ESCirit** [comment]
I duplicated the “Basic Example Notion Database” again and followed setup steps from beginning. This way the problem solved. 

But I still don’t know what is the problem in the beginning actually :)

**Comment by dvanoni** [comment]
@ESCirit, to be honest, I'm not sure what the problem was either. I don't think I've seen that specific error message before.

I'm glad you were able to resolve it!
