### ISSUE TITLE
Add Zotero note as plain text in Notion page

### ISSUE THREAD

**Issue by Lilianvallet** [dvanoni/notero#34]
Hi  @dvanoni,

Thanks for your work on this great plugin. I was wondering if you had  #planned to allow the inclusion of Zotero notes directly in a Notion page. Indeed, I took many notes in the "note" part of the Zotero application and I wanted to know if there was a simple way to display it as plain text inside the Notion page. 
So, it would be interesting to add a "Zotero note" template to allow the use of this option.

Thanks again for this plugin.

**Comment by Lilianvallet** [comment]
I just discovered that this improvement has already been suggested in #4 :

> I think notes generated by user should be sync to notion database too.

> I am here to offer my +1 to exporting both annotations and notes generated. My 2 cents toward making this scalable are : each annotation goes under the heading "annotation" and each note's content goes under the heading {note name} in the body of the page.

**Comment by dvanoni** [comment]
@Lilianvallet thanks for the feedback! Yes, this use case should be covered by #4, so I'm going to close this issue as a duplicate. Feel free to add a 👍 on #4!
