### ISSUE TITLE
sync from notion to zotero

### ISSUE THREAD

**Issue by jh-yi** [dvanoni/notero#342]
Hi thanks for the amazing plugin. 

I wonder if it is possible to sync changes from notion to zotero? Thanks a lot in advance! :-)

**Comment by dvanoni** [comment]
Hi @jh-yi, thanks for the kind words. 🙂

Unfortunately, syncing from Notion to Zotero is not currently possible. I have a [note](https://github.com/dvanoni/notero#how-to-sync-from-notion-back-into-zotero) about this in the readme:

> While this would be nice, it's unfortunately beyond the scope of this plugin. Getting updates from Notion into Zotero would require setting up a hosted service that subscribes to webhooks from Notion and then uses the Zotero API to update items in Zotero. Notion has yet to release official webhook support, but there are some third-party tools that can be used for this. In theory, this is technically possible, but it would be a separate project.
