### ISSUE TITLE
[Bug] Notero add-on still recognized but features are broken

### ISSUE THREAD

**Issue by FloG1** [dvanoni/notero#348]
Hello,
A few weeks ago, notero started not working correctly. Started with the Notero option under 'Tools' Menu not showing up, then references sometimes not syncing into notion even though I added the tag. Now the Notero option completely disappeared from the menu and nothing syncs anymore (when I update some details about a reference already synced or when I add a new one). The "Sync to Notion" option does not show up neither.
Note that in add-ons manager of Zotero, Notero is still there.

I'm running on Zotero 6.0.23 and Notero 0.4.13, Windows. I am not sure of when problems started because I did not use Zotero during 3-4 weeks between the end of August and middle of September. Before then all was working fine.

I tried to disable LibreOffice add-on as suggested issue #147 , without success.

**Comment by dvanoni** [comment]
Hi @FloG1, thanks for reporting.

It was [identified yesterday](https://github.com/dvanoni/notero/issues/147#issuecomment-1747580951) that version 0.4.13 of Notero only works with the latest version of Zotero (6.0.27). Can you try updating Zotero to see if that fixes your issue?

**Comment by Mela** [comment]
I'm on Zotero 6.0.27 but the Notero menu is missing and new items do not sync. Any suggestion what I can try?

**Comment by dvanoni** [comment]
Hi @Mela, would you be able to share a screenshot of the error console like the one that was shared in [this post](https://github.com/dvanoni/notero/issues/147#issuecomment-1747527674)? You can open it from the **Tools > Developer** menu, and then it would be great if you could search for messages including "notero" using the input field at the bottom left.

**Comment by Mela** [comment]
Hi @dvanoni . 

Here it is. Hope that helps.

![Bildschirmfoto 2023-10-19 um 00 00 04](https://github.com/dvanoni/notero/assets/361364/8fd018ba-b149-4e52-81f1-d50d41f45bdc)


Also: This are the last too items I've added to my synced collection. The one titled "True colors" synced, the one titled "Die Ansiedlung der Hugenotten" did not. The Notero note and tag is also missing in the last one. 

![Bildschirmfoto 2023-10-18 um 23 58 03](https://github.com/dvanoni/notero/assets/361364/bdbc11a9-d679-4aae-9a36-667fc70451e8)

Thank you! 

Mela

**Comment by Mela** [comment]
So ... after sending the screenshot I discovered, that my browser extension also stopped working. Thus I reinstalled Zotero stable 6.0.28 (was running Beta until now).
Now the Notero menu is available again.

**Comment by dvanoni** [comment]
I'm glad it's working again, @Mela!

The error message regarding `Zotero.getMainWindows` was throwing me off because I thought that was fixed in the latest version of Zotero. But I'm not sure exactly which changes are included in the latest versions of stable vs beta, so I'm glad that reinstalling stable seemed to fix it!
