### ISSUE TITLE
could not find database error

### ISSUE THREAD

**Issue by acethecurious** [dvanoni/notero#349]
**Describe the issue**
I have just attempted to connect Zotero and Notion using the Notero software, however Zotero produces the error "APIResponseError: Could not find database with ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" when I attempt to sync items to Notion. I have disconnected and reconnected Notero as a connection in Notion. I have double checked the database and secret code are correct. 

**Expected behavior**
My database in Notion to be populated with the collection I have specified in Notero preferences.

**Screenshots**
Notero is connected but the error still shows.
![image](https://github.com/dvanoni/notero/assets/147498601/984672c8-9cc5-41ac-8baf-b48e2825efb8)

**Comment by dvanoni** [comment]
Hi @acethecurious, would you mind sharing the link to your database and the value of the **Database ID** field you've entered in the Notero preferences? I'm wondering if there's something slightly off that I can spot. Thanks!

**Comment by acethecurious** [comment]
Thank you so much, David!!

Here is my database ID: d507019ae98346e484cb335fa44e2e54. And I think this is the link...https://www.notion.so/a24065177cfd4afaba4f31b2c066688a?v=3346762e4403498c9f0c179570dd75ca&pvs=4. It hsould just be called 'Literature review'. Let me know if that's not correct!

**Comment by acethecurious** [comment]
Oops! I'm so sorry to bother you with such a small thing! I'm not sure where I got that other value from then >< thank you so much for the help. I've done what you advised and it has worked perfectly :) thanks again!!
