### ISSUE TITLE
APIResonseError: Could not find database with ID

### ISSUE THREAD

**Issue by vlwbirds** [dvanoni/notero#353]
I checked the FAQ and didn't find this issue.

**Describe the issue**
I copied the integration key for the connection. Then, I followed the instructions for using the database ID from the URL, between the slash and the question mark. But I keep getting an error that says it can't find the database with the ID.

**To Reproduce**

1. Made a Zotero integration key on Notion
2. Enabled all content
3. Added connection to my Notion database 
4. In Zotero, I pasted the integration key
5. In Zotero, I copied the URL Database ID between the /..........? 
6. I imported pdfs into Zotero

**Expected behavior**
Fields should populate in my database such as Author, Title, etc

**Screenshots**
<img width="1196" alt="Screenshot 2023-10-26 at 4 35 58 PM" src="https://github.com/dvanoni/notero/assets/146786433/6ea75fc4-e85b-4ab3-b858-d1e7763615f3">

**Additional context**
I felt like I followed all the instructions. I cleared the Error Console before making the screenshot. I included the warning about unreachable code in the screenshot.

Thanks for making such a great tool! Hopefully I get it working.

**Comment by dvanoni** [comment]
Hi @vlwbirds, thanks for filing such a thorough issue! It sounds like you followed all the necessary steps, and that ID looks valid.

Would you mind sharing the full URL to your database and a screenshot of the connections popup like the one below? I can take a look and see if there's anything I notice that seems off.

Thanks!

<img width="493" alt="CleanShot 2023-10-26 at 17 09 32@2x" src="https://github.com/dvanoni/notero/assets/299357/bc7baa05-db66-4696-afec-516ab2f9b43d">

**Comment by vlwbirds** [comment]
Hi David,

Thanks for taking the time to look into this.

I grabbed a template from Notion to try to save some time, which maybe
causes the problem?

Here's the full URL

https://www.notion.so/6c4bd3276cec48e98487ab95b04a16a8?v=b25bf29d2f3744efa6a8a5c56e725d29

and a screenshot
[image: Screenshot 2023-10-27 at 12.41.51 PM.png]
Thanks

**Comment by dvanoni** [comment]
Hi @vlwbirds, thanks for sending the URL. Based on the structure, I'm pretty sure you have the database ID entered correctly into Notero.

It looks like your screenshot didn't come through over email. Can you try sending it through github.com instead?

Thanks!

**Comment by vlwbirds** [comment]
@dvanoni 
<img width="1543" alt="Screenshot 2023-10-28 at 10 08 21 AM" src="https://github.com/dvanoni/notero/assets/146786433/c9f03930-567f-486c-9ccb-7b2aac219653">

**Comment by dvanoni** [comment]
Thanks for sharing that, @vlwbirds. I don't see anything out of the ordinary here. This really has me stumped...

One more thing you might try is generating a new integration token by clicking the "Refresh" button on the "Secrets" section of your Notion integration. Perhaps that will reset something on Notion's side.

![CleanShot 2023-10-28 at 16 32 32@2x](https://github.com/dvanoni/notero/assets/299357/545a9159-d9ea-4537-b2d4-a768cb4703c0)

And just for completeness sake, you don't happen to have multiple integrations created on accident, do you? I've seen it happen before, so I just wanted to rule it out.

**Comment by dvanoni** [comment]
@vlwbirds, I recalled another issue (#68) where some folks were encountering the same problem. Does [this comment](https://github.com/dvanoni/notero/issues/68#issuecomment-1569648241) help at all?

> I may have found the problem. In my case I copied the Notion page ID instead of the database ID. It appears that when you first create an empty page and then add a database to it, the IDs will be different. I got the database ID by copying a link to a specific view and then extracting the ID from the link. Now it works :)

**Comment by dvanoni** [comment]
Solution [described here](https://github.com/dvanoni/notero/issues/68#issuecomment-1785840774):

> I solved it, but in a less than straightforward fashion. The token I copied directly from the key generator was wrong, apparently. What I did to make it work was open up the account settings in Notion, opened the connections side bar, then I clicked the individual ... settings for my notero connection and copied the token information from there.
