### ISSUE TITLE
Getting Zotero collection folder path as a property in Notion

### ISSUE THREAD

**Issue by pmmendoza** [dvanoni/notero#37]
#massive 🤩 #enhancement 
**Idea💡:** Have a property in the Notion database that indicates all folder paths of the entry via multi-select (e.g. "Methods/ML" if an entry is in your Zotero collection that is in the folder "ML" which is in the folder "Methods");

**Why❓:** 
- When working on several projects at once you may have the literature in separate folders in Zotero and on separate pages on Notion
- Instead of creating separate connections between the two you could simply create one Notero Literature database on Notion and then create linked databases on the project pages which have filtered views of the literature base (based on the folder position on Zotero)

Amazing addition would of course be if changes in Notion synced back to Zotero so that I could change collection membership of an entry in Notion and it would also be taken up in Zotero;

**Comment by dvanoni** [comment]
@pmmendoza, thanks for the nice issue write-up! This is exactly what I intend to do for #30. Does that issue capture your needs? If so, are you alright with closing this one as a duplicate?

**Comment by pmmendoza** [comment]
Uhh didn't see that one - that's amazing also already perfectly elaborated; 
Very much appreciated 🙏
