### ISSUE TITLE
APIResonseError: invalid request URL

### ISSUE THREAD

**Issue by SuwEw** [dvanoni/notero#373]
**Describe the issue**
Hi! Your design concept of Notero appealed to me and is undoubtedly a fancy plugin for scientific research. But I always get this report of URL error in my settings.
The error is **"APIResonseError: invalid request URL"**
I have double-checked the database ID following the format described in the [Configure Notion]. It is right and I have also re-installed Notero, re-added the integration in Notion, created new files in Notion, and restarted Zotero and Notion after each setup.

**Screenshots**
<img width="279" alt="截屏2023-11-02 21 55 00" src="https://github.com/dvanoni/notero/assets/95019198/f0f46771-4f3f-44e3-860f-364f23beac00">
I checked the error console, sorted by the keyword "notero" and got this picture.
<img width="752" alt="截屏2023-11-02 21 54 45" src="https://github.com/dvanoni/notero/assets/95019198/8d2ff194-7941-4f1c-a1b3-cdeed5ad4e08">

**Comment by dvanoni** [comment]
Hi @SuwEw!

Would you mind sharing the link to your database and the value you have set for the "Database ID" field in the Notero preferences? I can take a look and see if I notice any issues there since that's usually the cause of this error.

Thanks!

**Comment by SuwEw** [comment]
> Hi @SuwEw!
> 
> Would you mind sharing the link to your database and the value you have set for the "Database ID" field in the Notero preferences? I can take a look and see if I notice any issues there since that's usually the cause of this error.
> 
> Thanks!

Sure! The link of the database is https://www.notion.so/73a4512eafeb4642b488959b2816582e?v=d87c7a7a06ff40f48f83e2a384b9b09c&pvs=4 
And the Database ID in notion is notion.so/73a4512eafeb4642b488959b2816582e

Thanks for your reply

**Comment by dvanoni** [comment]
Thanks for sharing! It looks like the issue is that you have `notion.so/` in your database ID, but you'll want to remove that. The ID should just be `73a4512eafeb4642b488959b2816582e`.

Let me know if that helps!

**Comment by SuwEw** [comment]
> Thanks for sharing! It looks like the issue is that you have `notion.so/` in your database ID, but you'll want to remove that. The ID should just be `73a4512eafeb4642b488959b2816582e`.
> 
> Let me know if that helps!

This method works. I misunderstood the input should be `notion.so/` with the real correct part. 

Thanks for helping me solve the problem that has been bothering me for a long time!
