### ISSUE TITLE
APIResponseError

### ISSUE THREAD

**Issue by Tolulade05** [dvanoni/notero#387]
****Describe the issue****
My Zotero isn't syncing to the Notions page. I've followed all the steps but it keeps showing that an 
"APIResponseError: body failed validation. Fix one: body.parent.page_id should be defined, instead was 'undefined'. body.parent.database_id should be valid uuid, instead was '[81f5ee5678e94ba5a9cf165c205bbc5c?" '. 

It seems like Zotero is unable to find my notions page using the database ID I provided. 
What am I missing? 

****Expected behavior****
For Zotero to sync to Notions I receive the error message instead. 

**Screenshots**
I've attached a screenshot to the error message. I've successfully connected my Zotero to Notion before and I'm unsure why I am now getting this error message. 

**Additional context**
I have deleted all prior Zotero-Notion Pages and Documents and emptied the trash. 
<img width="215" alt="Notero Error Message" src="https://github.com/dvanoni/notero/assets/153023623/09d9bd15-dd10-430f-80cd-258d2cdc1e56">

**Comment by dvanoni** [comment]
Hi @Tolulade05, it looks like a question mark (`?`) was included at the end of your database ID field. You'll want to remove that in the Notero preferences.

Let me know if that resolves your issue!
