### ISSUE TITLE
Sync existing Zotero items

### ISSUE THREAD

**Issue by bvendsel** [dvanoni/notero#39]
I have everything up and functioning (for new articles) but can't for the life of me figure out how to have Notero go back and pick up the hundreds of existing papers. Is it possible to manually trigger a one-time import of all of those papers or do I need to export them and bring them back in fresh?

**Comment by dvanoni** [comment]
Hi @bvendsel, it should be easier to do this once #21 is implemented, but until then, I've found that the easiest way to trigger a sync of many items is to add a tag to them. Doing so should cause Notero to pick them up and sync them to Notion as shown in the video below. Let me know if this works for you!

https://user-images.githubusercontent.com/299357/150908961-e35323d3-a405-44e1-a316-3f692f618667.mp4

**Comment by bvendsel** [comment]
@dvanoni  you are a scholar and a gentleman. Worked like a charm. Thank you! I can't tell you how much this specific integration will help me.
