### ISSUE TITLE
Notero preference is not showing up in tools 

### ISSUE THREAD

**Issue by Aman-Basu** [dvanoni/notero#395]
**Describe the issue**
Notero preference is not showing up in the tools even after restarting Zotero. 
<img width="957" alt="Screenshot 2023-12-13 at 12 10 35 PM" src="https://github.com/dvanoni/notero/assets/62647860/54a84fc1-0dd8-4ba8-91c1-0be82949867c">
<img width="258" alt="Screenshot 2023-12-13 at 12 11 18 PM" src="https://github.com/dvanoni/notero/assets/62647860/0fa0757c-16ef-4319-9540-cff4e4a302ae">

I am running this on intel Mac and Zotero version 7.0.0-beta.53+969031a37
I used the Notero version 0.5.0

**Comment by Aman-Basu** [comment]
I found that it's the issue with the Zotero ver 7.0.0, which is a beta. For Zotero 6.0.30 it works fine.

**Comment by dvanoni** [comment]
Hi @Aman-Basu, thanks for reporting! I'm sorry this isn't more clear, but in Zotero 7 the Notero preferences have moved into a section in the main Zotero preferences. Are you able to find them there?

**Comment by dvanoni** [comment]
I've added a note about this to the README.
