### ISSUE TITLE
Unable to sync because of the notion API error

### ISSUE THREAD

**Issue by anatolii-kotov** [dvanoni/notero#40]
Hello,

I have some error when trying to sync to Notion. It's APIResponseError with ID: xxxxxxx-xxxx-xxxxx-xxxxx-xxxx. The problem is not with token, but the somehow with the ID.

![MupZVxLFfZ](https://user-images.githubusercontent.com/49878040/151820322-704eeeb9-13c3-4bc0-bfde-ec1043cbeaa8.jpg)
Zotero version: 5.0.97-beta.64+ae7bfe7f4

Thanks!

**Comment by dvanoni** [comment]
Hi @anatolii-kotov, I think I've seen an error like this before when Notero doesn't have access to the database in Notion. Did you perform the steps to [share your database](https://developers.notion.com/docs/getting-started#step-2-share-a-database-with-your-integration)?

If you click the **Share** button in the top-right of your database, you should see the Notero integration like this:

<img src="https://user-images.githubusercontent.com/299357/151826101-84951818-5324-4bbb-9c69-a2d431c6e990.png" width="396px" alt="share" />

Is that already set up?

**Comment by anatolii-kotov** [comment]
@dvanoni , yes, this step was missing. now everything is working. Many thanks for great plugin 👍
