### ISSUE TITLE
Authors split issue

### ISSUE THREAD

**Issue by nulllinhao** [dvanoni/notero#401]
**Describe the issue**
Hello!
Multi Authors were split by new line in the 0.5.0 version. They are split by space after updating to 0.5.1 (I also install some add-ons during the same period, maybe impact by one of them, not sure). Is there any way to back to split by new line? Many Thanks!

**Screenshots**
![image](https://github.com/dvanoni/notero/assets/37645035/1a832f75-1332-419c-ae3f-382990a8a236)

**Comment by dvanoni** [comment]
Hi @nulllinhao, thanks for reporting this! Version 0.5.0 completely overhauled the syncing code, and it looks like I introduced this bug there. I'll get a fix pushed out!

**Comment by dvanoni** [comment]
@nulllinhao, this should be fixed in version [0.5.2](https://github.com/dvanoni/notero/releases/tag/v0.5.2). Please let me know if it's working for you!

**Comment by nulllinhao** [comment]
> @nulllinhao, this should be fixed in version [0.5.2](https://github.com/dvanoni/notero/releases/tag/v0.5.2). Please let me know if it's working for you!

working!!!
