### ISSUE TITLE
Error: Failed to load HTML content

### ISSUE THREAD

**Issue by zhangj726** [dvanoni/notero#403]
Hi, when syncing items to Notion, error that "Failed to load HTML content" occured.

![image](https://github.com/dvanoni/notero/assets/148530302/8307dde1-0211-4e41-9edd-7438fd7eb20d)

**Comment by dvanoni** [comment]
Hi @zhangj726, thanks for reporting this. This error occurs when Notero is unable to load the content for one of your Zotero notes.

If you try to sync that note again, do you get the same error? Would you mind sending a screenshot of the note?

**Comment by FilipKaas** [comment]
I have the same problem, it seems to me that only Zotero titles that have notes (the yellow subfiles) associated to it create this problem. But not all of the notes are problematic.

**Comment by dvanoni** [comment]
Thanks for reporting, @FilipKaas. If you encounter this error again, would you mind sending a screenshot of the note content?

**Comment by FilipKaas** [comment]
Sure, I will send all that I find, when I get to my computer 🙂

Dne so 23. 12. 2023 20:44 uživatel David Hoff-Vanoni <
***@***.***> napsal:

**Comment by zhangj726** [comment]
Thanks for your quick response, @dvanoni. I find that Note (the yellow subfiles, same as @FilipKaas  reported) with translations automatically generated by plugin "Translate" would make this error.
![image](https://github.com/dvanoni/notero/assets/148530302/71d7e192-8353-490b-81e3-b00555b2c17f)

**Comment by FilipKaas** [comment]
From what I gather, I am almost sure that the notes that are created
automatically by Zotero (in my case those produced by the magic stick
button "Add Item(s) by Identifier") are the problem and it does not matter
what they look like. If I edit the note myself, the problem disappears
(even if I just delete and add the same character).

ne 24. 12. 2023 v 10:46 odesílatel zhangj726 ***@***.***>
napsal:

**Comment by dvanoni** [comment]
@zhangj726 @FilipKaas, I just released [v0.5.4](https://github.com/dvanoni/notero/releases/tag/v0.5.4) which I believe should fix this issue. Please give it a try and let me know if it works for you!

**Comment by zhangj726** [comment]
It works!!! Sincerely thanks to @dvanoni, for such an amazing speed of debugging!! thanks to  @FilipKaas for detailed report.

**Comment by FilipKaas** [comment]
Amazing work, thank you! Merry Christmas!
