### ISSUE TITLE
Collection Field not syncing

### ISSUE THREAD

**Issue by Calluna8122** [dvanoni/notero#426]
I'm trying to include a field in Notion that shows the Collections an item is in. 

I have created a property in Notion titled "Collections".

I tried setting the property as [text] and as [multi-select]. I also tried adding the collections I am syncing as options for the multi-select property.

The property remains blank even though all other information for the Zotero item is syncing.

**Comment by dvanoni** [comment]
Hi @Calluna8122, thanks for reaching out.

A multi-select property is the correct type to use. I'm not sure off the top of my head why it's not working. 🤔

Would you mind installing a test build of Notero and sending me a screenshot of the logs following these steps?

1. Install the test build from [here](https://nightly.link/dvanoni/notero/actions/runs/7498509922/notero-0.5.8-330.zip). (You don't need to unzip the file. You can install the zip file directly into Zotero.)
2. Open the Zotero Error Console from the menu **Tools > Developer > Error Console**.
3. Click the "Clear" button at the top of the Error Console.
4. Go back to the main Zotero window and sync an item to Notion.
5. Go back to the Error Console and take a screenshot of the logs. We should expect to see something like the image below.

Thanks!

![CleanShot 2024-01-11 at 22 13 02@2x](https://github.com/dvanoni/notero/assets/299357/1cb36ac7-c4ad-483a-a71e-d6c01e3af8da)

**Comment by LisaMMilchsack** [comment]
Hi @dvanoni, I had the same issue today and followed your instructions. The 'collections' field was synced using the test build but not the latest build (v0.5.14). Please, find the logs from the error console attached.

<img width="1045" alt="Screenshot 2024-02-01 at 13 58 19" src="https://github.com/dvanoni/notero/assets/49974138/3c8def3d-da40-4daa-aa89-ce665227d5c3">
<img width="1042" alt="Screenshot 2024-02-01 at 13 58 30" src="https://github.com/dvanoni/notero/assets/49974138/f0c01ea4-abc3-4758-957a-97d4702934a7">

**Comment by dvanoni** [comment]
Hi @LisaMMilchsack, thanks for sending the logs!

For the item named `Lotfollahi et al., 2023`, I see that Notero attempted to save a collection option named `CompMethods ▸ Perturbation modelling`. It looks like the request to Notion succeeded, so I'm not entirely sure why it's not appearing in Notion. I wonder if the Notion API is silently dropping that option for some reason... 🤔 The only thing I can think of is that perhaps there's a limit to how many options Notion allows in a **multi-select** property.

Would you mind running the following steps to see how many options you currently have for your `Collections` property?

1. Open **Tools → Developer → Run JavaScript**
2. Paste the below code
    ```js
    const database_id = Zotero.Prefs.get('extensions.notero.notionDatabaseID', true);
    const database = await Zotero.Notero.getNotionClient().databases.retrieve({ database_id });
    return database.properties.Collections.multi_select.options.length;
    ```
3. Ensure the "Run as async function" option is enabled
4. Click the "Run" button

This should result in something like the below screenshot. In this example, I have 109 options for my `Collections` property.

![CleanShot 2024-02-01 at 23 10 35@2x](https://github.com/dvanoni/notero/assets/299357/fe516201-2015-4873-8766-279c6bf2ae44)

**Comment by JayCunningham** [comment]
Hi @dvanoni, I'm having a similar issue when none of my Zotero files are syncing to the database now. I've tried uninstalling, disabling, reconfiguring, running error message, and still nothing. My database was syncing for a while and I recently noticed that it wasn't. Any thoughts on how to solve this?

**Comment by dvanoni** [comment]
Hi @JayCunningham, can you clarify which of the following you're encountering?

- When syncing an item, the sync fails with an error message.
- When syncing an item, the sync succeeds but no changes appear in Notion.
- Items do not _automatically_ sync as expected.
- Something else?

**Comment by JayCunningham** [comment]
> Hi @JayCunningham, can you clarify which of the following you're encountering?
> 
> * When syncing an item, the sync fails with an error message.

- The sync in Zotero appears to be successful. Also the small notification for Notero also appears, so I think this is working properly. 

> * When syncing an item, the sync succeeds but no changes appear in Notion.

- Correct, the sync in Zotero appears successful. 

> * Items do not _automatically_ sync as expected.

- The items do no appear in the Notero library at all. 

> * Something else?

**Comment by dvanoni** [comment]
Thanks for the info, @JayCunningham. I'm a bit stumped if it looks like things are successful within Zotero. 🤔 

Just to rule out some strange caching issue in Notion, are you able to open Notion in a private browser window and see if things load any differently there?

Another thing we can do is look at the sync logs using the steps I [listed above](https://github.com/dvanoni/notero/issues/426#issuecomment-1888494504). If you'd like to give that a try and post a screenshot, please use this more recent [test build](https://github.com/dvanoni/notero/actions/runs/7984963871/artifacts/1261982821).

**Comment by JayCunningham** [comment]
> Thanks for the info, @JayCunningham. I'm a bit stumped if it looks like things are successful within Zotero. 🤔
>  UPDATE: Some of the references from one of my collections just sync'd. Which again is weird because I have multiple collections indicated to sync, and there's definitely more than the 3 that's listed 
<img width="423" alt="image" src="https://github.com/dvanoni/notero/assets/20421990/5f87705e-cf13-43b0-b7c0-32b004a62174">

> Just to rule out some strange caching issue in Notion, are you able to open Notion in a private browser window and see if things load any differently there?
> I typically use the desktop app, but the web application still isn't populating differently. 
> The private browsers didn't make a difference. 
> Another thing we can do is look at the sync logs using the steps I [listed above](https://github.com/dvanoni/notero/issues/426#issuecomment-1888494504). If you'd like to give that a try and post a screenshot, please use this more recent [test build](https://github.com/dvanoni/notero/actions/runs/7984963871/artifacts/1261982821).
> And yes, I did follow those instruction, here is the updated log:
<img width="1035" alt="image" src="https://github.com/dvanoni/notero/assets/20421990/92523898-37df-472d-a176-3bd82182587d">

I'm not really sure what else to do. It's definitely disappointing because I love this tool.

**Comment by dvanoni** [comment]
@JayCunningham, how did you go about syncing those 3 items? Did you click "Sync to Notion" on individual items or on a collection in the left sidebar? Or did they automatically sync as you updated those items?

If you select a collection and click "Sync to Notion", do only some of the items end up showing up in Notion?

**Comment by JayCunningham** [comment]
Ahh, I see what is happening now! I didn't realize that I needed to 'sync to notion' within the Zotero collective navigation panel. 

Now that I am reorganizing and syncing the individual collections, the bibs are now populating. Maybe, this was a silly overlook, but I do think that reinstalling the add-on helped me notice this. 

Thanks for your attention and help!

**Comment by Franfranu** [comment]
"I'm experiencing an issue with my Notion database where only the 'name' property synchronizes with my Zotero collection, and none of the other properties do. I initially thought it might be because my Zotero is in Spanish and the database template is in English. However, even after changing the 'Authors' property to 'Autor,' it still doesn't work. Any suggestions on how to troubleshoot this issue?"

**Comment by dvanoni** [comment]
Hi @Franfranu, I believe `Authors` should be the correct name for the property. The property names need to match those listed in the [Notion Database Properties](https://github.com/dvanoni/notero#notion-database-properties) section of the readme, regardless of the language you use in Zotero (at least until #355 is implemented).

Did you happen to start with one of the [example databases](https://github.com/dvanoni/notero#example-notion-databases) linked in the readme? Those databases should be set up to work as is. If you haven't done so, you could try duplicating one of those into your Notion workspace to see if it works.

If that doesn't work, could you follow the below steps to send me some additional info?

1. From the Zotero menu, open **Herramientas > Desarrollador > Run JavaScript** (**Tools > Developer > Run JavaScript**)
2. In the left side of the **Run JavaScript** window, paste the following code:

    ```js
    const notion = Zotero.Notero.getNotionClient();
    const database_id = Zotero.Prefs.get('extensions.notero.notionDatabaseID', true);
    const database = await notion.databases.retrieve({ database_id });
    return database.properties;
    ```

4. Enable the "Run as async function" checkbox
5. Click the "Run" button at the top left
6. Copy the result from the right side of the window and paste it here (it should look like the below screenshot)

    ![CleanShot 2024-03-19 at 23 38 29@2x](https://github.com/dvanoni/notero/assets/299357/73547349-6dd3-44b8-a615-3291a4874866)

**Comment by dvanoni** [comment]
Closing this for now. Please feel free to reopen if you're still encountering this issue.

**Comment by milkybaba** [comment]
hihi! im having issues with my zotero library not automatically syncing into my notion despite having troubleshooting for all possible problems :(
