### ISSUE TITLE
Error when trying to sync

### ISSUE THREAD

**Issue by chingona-grenuda** [dvanoni/notero#427]
Error reads as "APIResponseError: body failed validation; body.properties.Collections.multi_select[2].name.length should be <= '100' instead as '118'.

This shows up for multiple items when trying to sync, and then cancels synchronization for the rest of the items.

![image](https://github.com/dvanoni/notero/assets/130931227/6de99852-1b67-421e-b5ee-aacdc54db7ab)

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dvanoni** [comment]
Hi @chingona-grenuda, thanks for reporting this!

This is the same issue described in #240. I still need to implement a proper fix, but to work around this for now you'll need to either shorten the names of some of your collections or reduce some of the nesting of collections. Please see #240 for more details and examples.
