### ISSUE TITLE
Notero Preferences Not Showing in V7 Beta

### ISSUE THREAD

**Issue by kikiyashi** [dvanoni/notero#432]
**Describe the issue**
Essentially the title - under the tools menu, the option for Notero Preferences is not there. I've tried reinstalling the Notero application, to no luck. I'm still able to sync to notion - it does it both automatically and the option is there to manually sync when I click on an item.

<img width="473" alt="Screenshot 2024-01-15 at 10 36 21 am" src="https://github.com/dvanoni/notero/assets/151099545/8d4ff490-e225-4847-b444-04141880a38f">

**Comment by dvanoni** [comment]
@kikiyashi, I've just released version 0.5.9 that restores the menu item, and it opens the new Notero pane in the main Zotero preferences window.
