### ISSUE TITLE
Notero preferences section can not be located.

### ISSUE THREAD

**Issue by bhosalems** [dvanoni/notero#445]
Not able to locate the Notero preferences within Zotero.

Zotero version : 6.0.15

![image](https://github.com/dvanoni/notero/assets/10846405/151db02c-a31a-4da5-b95f-be521103eb0f)

**Comment by dvanoni** [comment]
Hi @bhosalems, you may be encountering the issue [described here](https://github.com/dvanoni/notero/issues/147#issuecomment-1747580951) where Notero only works with at least version 6.0.27 of Zotero. Can you try updating Zotero to the latest version to see if that resolves your issue?

**Comment by bhosalems** [comment]
Thanks, it works now after updating.
