### ISSUE TITLE
Notero not syncing

### ISSUE THREAD

**Issue by peter716** [dvanoni/notero#450]
I am currently experiencing an issue with syncing my Zotero to Notion. Anytime I sync from Zotero, it does not reflect in Notion. In some cases, it reflects for a moment and then disappears. What could be the problem here?

**Comment by dvanoni** [comment]
Hi @peter716, I replied to your email but haven't heard back. Would you be able to send me a video of the issue you're seeing?

**Comment by peter716** [comment]
Hi David, sorry I forgot to get back to you. The issue seems to be fixed.
Turns out I wasn't loading the page again.
