### ISSUE TITLE
Note sync fails when encountering invalid URL

### ISSUE THREAD

**Issue by xp-one** [dvanoni/notero#458]
![屏幕截图 2024-01-29 231617](https://github.com/dvanoni/notero/assets/37956407/f6bb600c-2b17-458d-9312-a3c7313e6a4b)

**Comment by xp-one** [comment]
里面有链接就无法同步，删除链接可以同步，是自动跳转到条目 的链接。不知道怎么处理。

**Comment by xp-one** [comment]
![屏幕截图 2024-01-29 231945](https://github.com/dvanoni/notero/assets/37956407/90590f61-0298-4a55-8aac-6112aa6f4d9c)

**Comment by dvanoni** [comment]
Thanks for reporting this, @xp-one. I've also seen this issue myself. I have an idea for how to fix it.

**Comment by dvanoni** [comment]
@xp-one, this should be fixed in version 0.5.14. Please let me know if you have any other issues!
