### ISSUE TITLE
API Response Error

### ISSUE THREAD

**Issue by UchihaItachi777** [dvanoni/notero#471]
![image](https://github.com/dvanoni/notero/assets/125756537/fc694974-3350-4095-a3e4-e1467f1be461)

**Comment by dvanoni** [comment]
Hi @UchihaItachi777, please see how to handle this error [as described](https://github.com/dvanoni/notero#cant-update-a-page-that-is-archived) in the **Frequently Asked Questions** section of the README. Also see more discussion in #74 and #377.

Let me know if you have trouble resolving this.

**Comment by dvanoni** [comment]
@UchihaItachi777, I believe that issue should have been fixed by #459 which was released in version 0.5.14. Are you on the latest version of Notero? If not, could you update to the latest version and see if that fixes this issue for you?

**Comment by UchihaItachi777** [comment]
Oh, thanks! I've solved the problem
