### ISSUE TITLE
Synchronize Zotero's document merge operations to Notion

### ISSUE THREAD

**Issue by zhaoruifeng1211** [dvanoni/notero#473]
**problem
When I merge two duplicate entries in Zotero, there are still items in the notion database that should be deleted after the merge. At the same time, the zotero URL of these two data is different in the notion database. 

**request solution
After an entry merge operation is performed in Zotero, the merge result is automatically updated to the notion database

**Comment by dvanoni** [comment]
I think this might be the same as #46. @zhaoruifeng1211, would you agree?
