### ISSUE TITLE
Notero no longer "syncing" my sources: SYNC SAYS IT HAPPENS BUT IT DOESNT

### ISSUE THREAD

**Issue by mallorycerkleski** [dvanoni/notero#476]
**Describe the issue**
Notero no longer syncing my sources. When I ask to sync, it says it is syncing, but nothing is showing up in my Literature inbox. Nothing has been updated for almost 10 days. 

I started to look in some of the notion links to the sources and it says this:
```
{"containerBlockID":"5b9777f3-0872-425a-a8a8-b6a61a869225","notes":{"75XKDMJR":{"blockID":"29b48bd6-4dc9-4682-86db-c9b7bcd849b3","syncedAt":"2024-02-28T13:43:50.487Z"}}}
```

I am not sure what this could mean, but those with this are not showing up in notion and those without it are still there. HELP!

**Comment by dvanoni** [comment]
Hi @mallorycerkleski, thanks for sharing that info. I wonder if there has been an issue on Notion's side recently. Some other Notero users have also mentioned issues where Notero says it syncs but then the items don't appear in Notion (#450, #475).

If you have a Notion link attachment in Zotero, you should be able to use that to find the item within Notion.

- If you use the Notion desktop app, double-clicking the link attachment should take you to the item in the Notion app.
- If you use Notion in your browser, you can get a link to open in your browser by copying the URL from the link attachment and changing the `notion://` prefix to `https://`.

If you try one of these options, are you able to find the item in Notion?

**Comment by mallorycerkleski** [comment]
Hello,
After I tried doing this--they all appeared magically.

Thank you so much for your help.

Mallory

**Comment by mallorycerkleski** [comment]
And now--with another update its gone. It seems for the first minutes that
I search the link, the sources appear, it goes from 489 to 589 sources,
within seconds and then after a bit they disappear again...

Mallory

**Comment by dvanoni** [comment]
Hi @mallorycerkleski, the screenshot didn't come through over email. Would you mind posting it in this thread in your web browser?

Based on your description, I think this may be an issue on Notion's side rather than something in Notero. I'll take a look at your screenshot and see if I have any better guesses as to what's going on.

**Comment by mallorycerkleski** [comment]
Hello,
Thank you for getting back to me. In the end it was a huge mess, i realized
zotero sources were all connected to 3 different databases and so i had
notes all scattered and messy.

i decided to delete every notero link and redo the connection and sync.

it’s all good now.

Mallory

**Comment by dvanoni** [comment]
I'm glad you were able to figure it out!
