### ISSUE TITLE
Zotero URLs not populating for newly added items

### ISSUE THREAD

**Issue by bbutler3** [dvanoni/notero#486]
**Describe the issue**
After the initial sync of my Zotero libraries to Notion, the "Zotero URL" property was populated nicely for all items. Since I did the initial setup, anytime I add a new item to Zotero, the URL is not populated by Notero in Notion. It does seem to have happened for two specific items, but I may have added it manually (I don't remember). For the vast majority of newly added items, no URL is shown.

**To Reproduce**
1. Do the initial Notero setup and sync.
2. Add a new item to Zotero (using the web browser extension), and allow it to auto-sync to Notion.
3. The Zotero URL property is not populated in the Notero database for the new item.

**Expected behavior**
I expected the Zotero URL to get synced for new items just as it was for old ones.

**Additional context**
I've set up the Requestly web extension to make the Zotero links properly link to the desktop app, so having the URLs is especially useful for me to quickly navigate to the PDFs.

**Comment by dvanoni** [comment]
Thanks for the issue report, @bbutler3. I've just tested with Notero 0.5.15 in Zotero 6.0.35 on macOS, and I haven't been able to reproduce the issue yet.

One possibility I can think of: is the property in your Notion database named `Zotero URL` or `Zotero URI`? I notice that you used `Zotero URL` in the issue description, but the property needs to be named `Zotero URI` in order to work.

**Comment by bbutler3** [comment]
I feel a bit silly... I now remember renaming to URL a while back, possibly because I thought the I was a lowercase L (typo)? Of course I should have remembered I did that before and realized it could lead to the issue. I corrected the column name and added another item and everything works properly.

One question, though: is there an easy way to manually re-sync the previous items with missing links such that they get populated? I'm not seeing an option for that. 

Thanks for your help!

**Comment by dvanoni** [comment]
I'm glad we figured it out!

You should be able to manually re-sync items by right-clicking on them and selecting "Sync to Notion." You can also do this with multiple selected items at once.

**Comment by bbutler3** [comment]
The re-sync got all the links populated and everything works now. Thanks again! Hopefully this thread might at least help somebody else who does the same thing as me in the future. Otherwise, sorry to waste your time. Thanks for the great software :)

**Comment by dvanoni** [comment]
Not a waste of time at all! Always happy to help. 😄 

We'll be able to avoid this issue altogether once #355 is implemented.
