### ISSUE TITLE
Not allowed to configure database ID in Notero

### ISSUE THREAD

**Issue by glycohezhu** [dvanoni/notero#488]
Dear Developpers, 
Thank you for creating this cool tool! When I attempted to use Notero, I encountered an issue where I couldn’t input or paste the database ID, as shown in the figure below. Do you have any suggestions on how to resolve this?
Some software information for your reference. 
- OS: MacOS Monterey 12.7.1
- Zotero version: 6.0.37
- Notero version: 0.5.15
![image](https://github.com/dvanoni/notero/assets/17235102/24a793de-f2c7-4d62-adcf-37b1617a963b)
Thanks for your help!

**Comment by dvanoni** [comment]
Hi @glycohezhu! The setup process has slightly changed recently, so you no longer need to manually input your database ID. The grayed-out field is a drop-down that's supposed to populate with names of the databases that Notero has access to.

I see in your screenshot it says "no databases are accessible." Can you retry step 4 in the [Configure Notion](https://github.com/dvanoni/notero?tab=readme-ov-file#configure-notion) section of the readme to ensure your database is connected to the Notero integration?

**Comment by glycohezhu** [comment]
Hi @dvanoni, it works now. Thank you very much.
