### ISSUE TITLE
expand syncable zotero item properties

### ISSUE THREAD

**Issue by pmmendoza** [dvanoni/notero#49]
It would be great to be able to sync more properties from Zotero to Notion;

A) Ideally it would be possible to automatically take over any unique Zotero property name into a Notion Database column (e.g. by simply creating a column in the linked Notion database that's called "Publication" you would get any Zotero item property that's called "Publication") - the advantage here is that notero could easily be expanded to new item properties in Zotero (e.g. created by an add-on).
 
B) Alternatively one could do it manually for every property; in order of relevance from my perspective are: Publication, Extra (this is the comment column for e.g. citation counts), Place, Date Added / Modified;

---
Again I leave a comment/idea for an enhancement here as I still haven't acquired the necessary skills to contribute to this project personally; I hope I'll get there at some point, for now I am thankful for all the contributors 🙏

**Comment by dvanoni** [comment]
@pmmendoza I like this idea! I have some initial thoughts about it.

I think it might be good to make this a manual opt-in rather than automatically syncing any properties that have a matching name. I'm just thinking that there might be a case where someone wants to use a property in Notion for their own purposes and there happens to be a property in Zotero with the same name. What might be nice is to make this fully configurable so you can choose exactly which properties you want to sync from Zotero to Notion, and you can name them whatever you want.

Something that might be challenging about this is that the properties in Zotero are retrieved in all kinds of different ways (see [notero-item.ts](https://github.com/dvanoni/notero/blob/main/content/notero-item.ts)). I'm hoping that the properties that aren't "built in" to Zotero might have a more generic way of accessing them which would make it more feasible to implement this.

**Comment by ThomasDeLange** [comment]
I would also really like a Date Added sync for in Notion. The Notion Date added is not alway reliable. I could use it to see how much time it took for added to Zotero untill finished review.

**Comment by patrickmesana** [comment]
Would be nice to have the Citation Key synced when detected

**Comment by dvanoni** [comment]
[Version 0.4.7](https://github.com/dvanoni/notero/releases/tag/v0.4.7) now syncs the `Date Added` property, thanks to the contribution from @lsc64!

**Comment by justinqi2** [comment]
我已收到你的邮件~

**Comment by leylime** [comment]
Hello - apologies if I'm missing something really obvious here but I do not see some of the properties you've mentioned, including Abstract, Date Added and Collections (which is the one I really need). They simply do not come up in the list of properties under Shown in table or Hidden in table (or under deleted). I've really customised my Notion database/views so I'm really keen to fix this without having to delete and start over - do you think there might be a way to do this? I'm on Zotero 6.0.27 and Notero 0.4.13. I'm using the Notion desktop app but can't see the properties on the web app either.
Thanks so much!

**Comment by justinqi2** [comment]
我已收到你的邮件~

**Comment by dvanoni** [comment]
Hi @leylime!

If you're not seeing those properties at all, you should be able to add them yourself via the **+ New property** button in Notion. You'll need to ensure the names and types of the properties exactly match what's [specified in the readme](https://github.com/dvanoni/notero#notion-database-properties).

Let me know if that works for you!

**Comment by leylime** [comment]
> Hi @leylime!
> 
> If you're not seeing those properties at all, you should be able to add them yourself via the **+ New property** button in Notion. You'll need to ensure the names and types of the properties exactly match what's [specified in the readme](https://github.com/dvanoni/notero#notion-database-properties).
> 
> Let me know if that works for you!

It did work - thank you so much! Much appreciated.

**Comment by elisehellwig** [comment]
Seconding adding the "publication" and "extra" properties. "Series title" would also be very helpful.

**Comment by justinqi2** [comment]
我已收到你的邮件~

**Comment by dvanoni** [comment]
Happy holidays! I've just released [v0.5.5](https://github.com/dvanoni/notero/releases/tag/v0.5.5) which adds support for syncing the following properties:

| Property Name | Property Type |
|--------|--------|
| `Date Modified` | Date |
| `Extra` | Text |
| `Place` | Text |
| `Proceedings Title` | Text |
| `Publication` | Text |
| `Series Title` | Text |

I still want to add support for customizing the properties that can be synced. I'm tracking that work in #355, so please follow along there if you're interested!

**Comment by elisehellwig** [comment]
Thanks this is so helpful!

--
Elise Hellwig
Research Data Scientist, she/her
UC Davis DataLab: Data Science and Informatics
***@***.******@***.***>, 370 Shields Library

From: David Hoff-Vanoni ***@***.***>
Date: Sunday, December 24, 2023 at 11:01 PM
To: dvanoni/notero ***@***.***>
Cc: Elise C Hellwig ***@***.***>, Comment ***@***.***>
Subject: Re: [dvanoni/notero] expand syncable zotero item properties (Issue #49)

Happy holidays! I've just released v0.5.5<https://github.com/dvanoni/notero/releases/tag/v0.5.5> which adds support for syncing the following properties:
Property Name
Property Type
Date Modified
Date
Extra
Text
Place
Text
Proceedings Title
Text
Publication
Text
Series Title
Text

I still want to add support for customizing the properties that can be synced. I'm tracking that work in #355<https://github.com/dvanoni/notero/issues/355>, so please follow along there if you're interested!
