### ISSUE TITLE
Publication (Journal) didn't sync.

### ISSUE THREAD

**Issue by pekideer** [dvanoni/notero#493]
**Describe the issue**
Thanks the author for this incredible plug-in! But I met something wrong when syncing the item into Notion. The property of "Journal" shows blank (not syncing correctly) after I tried some items (see first Fig). I have no idea why this happened as you have added new feature in latest version that allows extracting "Publication" into Notion. I somewhat noticed that I used Etheral Style-A plug-in for better appearance (see second Fig), so could it block down the transformation of "Journal" to Notion?
**To Reproduce**
**Expected behavior**

**Screenshots**
![image](https://github.com/dvanoni/notero/assets/27672078/21b967ae-4452-4d21-a6a7-27b9d0e587e5)
![image](https://github.com/dvanoni/notero/assets/27672078/f31bf9d9-b9dc-40e7-813a-5412127169b6)
**Additional context**

**Comment by pekideer** [comment]
@dvanoni I tried ban and excluded the influence of the plug-in Ethereal style on this issue. 🙏 Could you help check the reason? Or folks who also meet this problem could comment following this issue?

**Comment by dvanoni** [comment]
Hi @pekideer, can you try changing the name of the property in Notion from `Journal` to `Publication`? Currently, Notero only syncs properties if they're named exactly what it expects, and `Journal` is not one of the properties it expects.

**Comment by dvanoni** [comment]
Closing this for now. Please feel free to reopen if you're still encountering this issue.
