### ISSUE TITLE
BibTeX citation key as Notion page title

### ISSUE THREAD

**Issue by dvanoni** [dvanoni/notero#5]
A BibTeX citation key as the name is a good idea! If that's straightforward to add, it would be a nice to have the option. Plus, citation keys are unique, helping in the case where you have two papers by the same author in the same year. That being said, the current APA style does look good for inline citations in Notion.

![Screenshot 2021-10-07 at 09 48 33](https://user-images.githubusercontent.com/43786145/136351525-59e2cbc3-b447-4bb6-895f-e62afdbe91d2.png)

_Originally posted by @alexlyttle in https://github.com/dvanoni/notero/issues/1#issuecomment-937588773_

**Comment by hengfei-wang** [comment]
Thank you for your impressive work. It means a lot to me.

Please use citation keys as the name. Usually, I find a paper using the tile instead of the author's name. And citation keys usually include some pieces of the paper title which is quite useful for finding a paper page in Notion. Hope to see this feature in the next version.

**Comment by dvanoni** [comment]
@retorquere, I'm hoping to get some input from you as a fellow Zotero plugin developer! I have some questions about the correct way to integrate with BBT.

- To get the citation key for an item, is it as simple as calling `item.getField('citationKey')`, or is there a different approach to use?

- Do you have a recommendation for how to best determine if BBT is installed? I'm thinking something like this?

      const addon = await AddonManager.getAddonByID('better-bibtex@iris-advies.com');
      return addon && addon.isActive;

Thanks!

**Comment by retorquere** [comment]
> To get the citation key for an item, is it as simple as calling item.getField('citationKey'), or is there a different approach to use?

This is indeed the correct way, and it will simply roll over to the native citation key field when Zotero adds their own support for it.

> Do you have a recommendation for how to best determine if BBT is installed? I'm thinking something like this?

That will do it; not that for Zotero 7, BBT can be installed/uninstalled while Zotero keeps running, so it's not a one-time check you can do. If you need a synchronous way to test for presence, you can test for `Zotero.BetterBibTeX`, but on Zotero 6, that has an edge case whene BBT is uninstalled, but Zotero has not been restarted yet.

**Comment by dvanoni** [comment]
Thanks for the prompt and helpful feedback, @retorquere!

**Comment by dvanoni** [comment]
This feature has (finally) been released in [v0.5.1](https://github.com/dvanoni/notero/releases/tag/v0.5.1)! 🎉
