### ISSUE TITLE
TypeError: style.getCiteProc is not a function

### ISSUE THREAD

**Issue by jianmhuang** [dvanoni/notero#514]
After installing the notero plug-in, the notion folder is synchronized, but you cannot syncing items to notion in zotero. Displays "TypeError: style.getCiteProc is not a function" when synchronizing.

**Comment by dvanoni** [comment]
Similar issues have been reported previously in #12 and #258. I believe the primary solutions in those were:

- Ensuring the `American Psychological Association 7th edition` style was installed (https://www.zotero.org/styles/apa)
- Ensuring an item format is selected on the Export tab of the Zotero preferences

@jianmhuang would you mind checking the above and let me know if there's anything there that helps?

**Comment by dvanoni** [comment]
Closing this for now. Please feel free to reopen if needed.
