### ISSUE TITLE
API Response Error: Can't edit block that is archived.

### ISSUE THREAD

**Issue by nuyhej** [dvanoni/notero#525]
![image](https://github.com/dvanoni/notero/assets/174284477/5be340ef-5340-4636-a213-2b309e0de8de)

**Describe the issue**
First off, thanks for making this awesome API!
When I try to add articles or change my tag, this error image pops up and does not sync with my Notion workspace.

**Comment by jadna** [comment]
I have the same problem

**Comment by dvanoni** [comment]
Hi @nuyhej @jadna, thanks for reporting this. I think I may have recently fixed an issue related to this. Can you confirm that you're using the latest version of Notero (0.5.17)?

**Comment by nuyhej** [comment]
![image](https://github.com/dvanoni/notero/assets/174284477/0f9e9bcc-2c1d-46ff-96f7-a70630c0025c)

yes, it does seem like i have the latest version!

**Comment by nuyhej** [comment]
for some reason, my problem has been solved, but I would love to know how to handle it if it comes up again

**Comment by dvanoni** [comment]
@nuyhej, I'm glad it's working for you!

On the latest version of Notero, I believe if you encounter that error again it should show the name of the Zotero item that the error occurred on. The error indicates that a Notion page may have been deleted, so hopefully you can use that item name to find the corresponding page in Notion's trash and then either restore it or permanently delete it.

**Comment by nuyhej** [comment]
Alright thanks for the information! 
Thank you always for developing such wonderful add-on.

Wish you the best!
