### ISSUE TITLE
Error: this.itemProgress.setIcon

### ISSUE THREAD

**Issue by he167** [dvanoni/notero#536]
Hello,

thank you for the great integration tool. I succsessfully conected zoteero with notion, but everytim I change something in zotero the following comes up: TypeError this.itemProgress.setIcon is not a function

Do you know how to fix it?  

Thank you for your help.

**Comment by dvanoni** [comment]
Hi @he167 👋 

This sounds similar to #500 which should have been fixed in Notero v0.5.16. Can you confirm which version of Notero you're using?

**Comment by vietpcong** [comment]
Hello,
great tool & the sync is working, thank you!
Im also getting this Error now - i installed zotero and notion and notero today. Just to share even though its old post. T

**Comment by dvanoni** [comment]
Hi @vietpcong, could you please share which versions of Zotero and Notero you're using?

**Comment by vietpcong** [comment]
Hi, sorry that im stupid.. i indeed downloaded the old Zotero not the v1 & it fixed it instantly.. thank you for being kind and answering still :)
