### ISSUE TITLE
Cannot change destination database

### ISSUE THREAD

**Issue by startledstarfish** [dvanoni/notero#542]
**Describe the issue**
I'm trying to change the database to sync to but the Database section under Notero Preferences just presents a dropdown list of one database instead of enabling me to enter a different database ID. I tried to refresh the integration token but that didn't change it.

**To Reproduce**

1. Go to Notero Preferences (in Zotero)
2. Click on Database ID
3. See drop down list only.

**Expected behavior**
I expected to be able to add a different database by entering the new ID.

**Screenshots**
![image](https://github.com/user-attachments/assets/9d41bffe-815f-40a2-adfb-1616adf6da51)

**Comment by dvanoni** [comment]
Hi @startledstarfish,

Recent versions of Notero no longer have a field to paste in a database ID. Instead it now has that dropdown, and you should be able to select any database that you've connected to Notero within Notion.

Is that "lit review zotero" database not the one you want to use? Is there a different database you're expecting to see?

**Comment by startledstarfish** [comment]
No, I was hoping to change the destination to a different database in
Notion.

I assume you can only sync to one database at a time (do correct me if I’m
wrong), but would the drop down in theory allow me to change which one?

**Comment by dvanoni** [comment]
If you'd like to use a different database, you'll need to repeat **step 4** in the [Configure Notion](https://github.com/dvanoni/notero?tab=readme-ov-file#configure-notion) section of the README to connect the Notero integration to your desired Notion database. Once you've done that, the new database should appear in the dropdown in Notero Preferences. You'll probably need to close the window and reopen it in order for the dropdown to refresh.

And yes, currently you can only sync to one database at a time. We're tracking support for multiple databases in #119.

I should also note bug #241 which may be related to this if you've started syncing items to one database and then want to switch to a different database.

Let me know if this helps!

**Comment by dvanoni** [comment]
@startledstarfish, were you able to select your desired database?

**Comment by startledstarfish** [comment]
That seems to have worked - thank you so much for your help.
