### ISSUE TITLE
TypeError: style.getCiteProc is not a function

### ISSUE THREAD

**Issue by artilleryyy** [dvanoni/notero#543]
**Describe the issue**
When I tried to synchronize the item, I got 'TypeError: style.getCiteProc is not a function'. I tried to disable all of my add-ons except for Notero, but the error persisted.

However, I suspect that it's because I have used the "zotero style" add-on and there are some unsupported columns. I have no idea how to solve this problem on my own.

**To Reproduce**
My Zotero version is 6.0.37 on macOS, and I have indeed installed lots of add-ons...
![CleanShot 2024-08-22 at 17 20 40@2x](https://github.com/user-attachments/assets/440e4fe0-82ec-4de3-a932-937c5f5994dc)

**Screenshots**
![CleanShot 2024-08-22 at 17 15 21@2x](https://github.com/user-attachments/assets/4d55b08c-9bd7-41ae-9647-dc5fada5a864)

**Comment by dvanoni** [comment]
Similar issues have been reported previously in #12 and #258. I believe the primary solutions in those were:

- Ensuring the `American Psychological Association 7th edition` style was installed (https://www.zotero.org/styles/apa)
- Ensuring an item format is selected on the Export tab of the Zotero preferences

@artilleryyy would you mind checking the above and let me know if there's anything there that helps?
