### ISSUE TITLE
Cannot install plugin in Zotero 7.0.3 (64bit)

### ISSUE THREAD

**Issue by ltestut** [dvanoni/notero#559]
**Describe the issue**
In the 64-bit windows version of Zotero (7.0.3) when I want to install the plugin from file (notion 0.3.5.xpi) it says this version is incompatible with zotero. 

Is there plan to make your plugin working with version 7 of Zotero, would be great ! Thanks

**Comment by dvanoni** [comment]
Hi @ltestut, Notero has been compatible with Zotero 7 for about a year. The version you installed (v0.3.5) is over two years old.

Please install the latest version ([v0.6.2](https://github.com/dvanoni/notero/releases/tag/v0.6.2)) which works with Zotero 7 and has more features and fixes.

Can I ask how you were directed to install v0.3.5?

**Comment by dvanoni** [comment]
@ltestut, were you able to install the latest version of Notero in Zotero 7?

**Comment by dvanoni** [comment]
Closing this for now. Please feel free to reopen if needed.
