### ISSUE TITLE
"%S" Error message when attempting to install 

### ISSUE THREAD

**Issue by studentface** [dvanoni/notero#561]
Hi David, 
I was trying to download the newest release of Notero but I keep getting the same error message when trying to install the add-on from file. The error is this:

The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.

**To Reproduce**

1. Download the latest file from GitHub (in this case v.0.6.2) 
2. Open Zotero application
3. Click on 'Tools'
4. Scroll down to 'Add-ons'
5. Click on 'Tools for all add ons'
6. Scroll down to 'Install add-on from file'
7. See error

**Expected behavior**
I was expecting to install Notero to my Zotero application in order to be able to move on with the integration process. 

Thank you in advance!
![error](https://github.com/user-attachments/assets/2b67e6fe-6631-463f-a9af-74cf53776c95)

**Comment by dvanoni** [comment]
Hi @studentface, thanks for the thorough report!

The latest version of Notero is indeed incompatible with Zotero 6 and now requires upgrading to Zotero 7. If you can upgrade Zotero to version 7, I would highly recommend that. If that's not possible, you should be able to install Notero [v0.5.17](https://github.com/dvanoni/notero/releases/tag/v0.5.17).

**Comment by studentface** [comment]
Hi @dvanoni, 
That worked like a charm! :) Thank you so much! Sorry for not seeing there was a new Zotero update 😅

**Comment by dvanoni** [comment]
I'm glad that worked! Enjoy Zotero 7. It's really nice!
