### ISSUE TITLE
TypeError: NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by SJPhilippov** [dvanoni/notero#578]
**Describe the issue**
Unable to sync with Notion database after the initial setup following directions on Notero's GitHub page.  It looks very similar to #478 

Zotero 7.0.5
Notero plugin 0.6.3

**Screenshots**
Shows the following Error:
<img width="321" alt="Screenshot 2024-09-13 at 14 36 25" src="https://github.com/user-attachments/assets/92d6232c-d6c5-4aaf-94da-72f9f255d864">

Settings:
<img width="1435" alt="Screenshot 2024-09-13 at 14 31 58" src="https://github.com/user-attachments/assets/4f6b3a98-7dd9-4deb-9068-6783ee8969cd">

Console:
<img width="790" alt="Screenshot 2024-09-13 at 14 38 14" src="https://github.com/user-attachments/assets/fab26066-a290-4454-8439-ffa3b027a8ad">

Any help would be appreciated!

**Comment by dvanoni** [comment]
Hi @SJPhilippov, thanks for reporting this!

This does look very similar to #478 and #51 before that. Unfortunately, I've never discovered any solution for this other than having folks investigate their network setup.

Are you using Zotero while on a work/school network, or is this happening on your home network? Are you using a VPN at all, and if so are you able to try disabling that?

**Comment by SJPhilippov** [comment]
Hi @dvanoni, thanks for the prompt reply! 

I've finally figured out the issue. I bet you'll be entertained by what was causing it as much as I am:

My MacBook time was off by like 10 minutes, even though it was set to sync automatically with Apple services.

Looks like I'm not alone in this: https://www.reddit.com/r/apple/comments/84cril/my_mac_shows_the_wrong_time_even_though_its_set/

When I reset it to the actual time, everything started working!

**Comment by dvanoni** [comment]
Consider me entertained! 😄

It's really interesting how many things fall apart when clocks are out of sync. I'm glad you figured it out!
