### ISSUE TITLE
can we make the structure of notion the same as zotero collections?

### ISSUE THREAD

**Issue by fredericky123** [dvanoni/notero#58]
Right now, all items are in the same folder in Notero, can we make the structure of notion the same as zotero collections
(The same item can exist in different folders)

**Comment by dvanoni** [comment]
Hi @fredericky123, thanks for the feedback!

There was some discussion around this topic in #6, and the decision was made to sync to a single Notion database for now. To achieve something similar to what you're asking, the idea we had was to sync a `Collection` property into Notion as described in #30. Then you could make as many different views of that database as you wanted based on the `Collection` property or any combination of other properties. This felt like the more "Notion way" of doing things.

Do you think having a `Collection` property in Notion as described in #30 would meet your needs?

**Comment by fredericky123** [comment]
Thanks @dvanoni ! This is exactly what I want. Have it already been realized? How to configure it?
By the way, when enable the collections to sync, can we have a toogle to sync all collections? Right now, we have to choose each single collection, since I have a lot of collections, it seems time-consuming to do this.

**Comment by dvanoni** [comment]
@fredericky123, unfortunately this functionality isn't built yet. Keep an eye on #30, and I'll be sure to post an update when it's ready.

I pulled out your second question into its own issue so we can track that separately: #63 

I'm going to close this issue as I believe we should have these points covered by #30 and #63. Feel free to add your input on those!
