### ISSUE TITLE
Syncing Items to Notion

### ISSUE THREAD

**Issue by DavidTetz** [dvanoni/notero#580]
When syncing from Zotero I get following Error Message:

TypeError:
this.itemProgress.setlcon is not a
function

It does not seem to interfere with the syncing progress since everything I want to have synced is being synced, however the error messages are quite annoying since they stay around and stack on top of each other. When trying to remove the error message it always switches back into the Zotero App which further hinders workflow.

This happens when manually syncing via right click -> Sync and also while automatically syncing, it does not seem to pop up for every sync while syncing multiple items however

![Bild 23 09 24 um 10 23](https://github.com/user-attachments/assets/d64365c5-3cc9-4f60-ac6f-9274c3fe6355)

Im using the Advanced Notero template and have the latest Zotero and Notion Update. Im on Mac OS Sequoia.

Thanks in Advance

**Comment by dvanoni** [comment]
Hi @DavidTetz, this sounds like #500 which was fixed in Notero v0.5.16. Can you check to see if you're on the latest version of Notero?

**Comment by dvanoni** [comment]
Hey @DavidTetz, Notero supports syncing notes as page content in Notion. Please see the **Syncing Notes and PDF Annotations** section of the README for instructions on how to use it, and let me know if you have any questions!

**Comment by DavidTetz** [comment]
Issue is fixed and notes are syncing, thanks a lot!! One Last question, is there a way to make the notes appear in the table like the other properties? 😀

**Comment by dvanoni** [comment]
I created #590 to track the request for syncing notes as a database property.
