### ISSUE TITLE
Sync changes in collection

### ISSUE THREAD

**Issue by marcelowoo** [dvanoni/notero#581]
Hi,

Thanks a lot for this amazing add-on.

**Problem**
Once a paper (or reference) in Zotero has been synced to Notion, if I change the paper's collection (folder) in Zotero, the change is not updated in the "Collections" field in Notion.

**Ideal solution**
I'd like the changes in the paper's collection in Zotero to be updated in Notion.

**Alternatives I've considered**
I couldn't find any convenient workaround.

Thanks a lot!

**Comment by marcelowoo** [comment]
To add: I did try to right-click and select "Sync to Notion", but the "Collection" field still doesn't update.

**Comment by dvanoni** [comment]
Hi @marcelowoo, thanks for reporting this. This feature should be supported (I just tested it myself), so I'm curious why it's not working for you.

Does the "Collections" property show the first collection an item is added to, or is it not showing any collections at all?

Would you mind sending a screenshot of the error console showing the data that's being synced for one of your items in a collection? I'm specifically hoping to see the values being synced for the `Collections` property.

Below is a video showing how to find the `Collections` property in the error console.

Thanks!

https://github.com/user-attachments/assets/7af1cc0d-918b-4f5d-83b8-2382272352d7

**Comment by Pedrodas1** [comment]
Hi...

I didn't know it was possible to sync the collection automatically until I saw this.

I followed the video instructions, but it seems it doesn't show the Collections property:

![image](https://github.com/user-attachments/assets/0181747a-089e-48b6-9a3a-0de0883ae0cb)

I have the latest version of Zotero and Notero:

![image](https://github.com/user-attachments/assets/e95afdd3-22c4-4e5b-bc1f-ab4475cb278d)

**Comment by dvanoni** [comment]
Hi @Pedrodas1, have you added a multi-select property to your Notion database named `Collections`? It will need to have that exact type and name in order for Notero to sync it.

**Comment by dvanoni** [comment]
@marcelowoo @Pedrodas1, are you still having issues with this?

**Comment by Pedrodas1** [comment]
Hi,

Apologies for the confusion earlier. You were correct. It turns out the issue was due to a missing 's' in "Collections" in the database name.

**Comment by dvanoni** [comment]
I'm glad you got it working, @Pedrodas1!

I'm going to close this issue, but @marcelowoo let me know if you're still having trouble.
