### ISSUE TITLE
Notes not syncing from Zotero to Notion

### ISSUE THREAD

**Issue by vpninfodk** [dvanoni/notero#584]
Notes from Zotero do not sync to Notion.

- I have the latest versions of Zotero and Notero.
- 'Sync notes' is enabled in Notero properties in Zotero.
- I have tried removing the connection in Notion and create it from scratch.
- It worked when I first installed the integration. However, I got an error message every time something was updated and autosynced. I googled a solution which was to install and switch to the APA citation style.

**Comment by vpninfodk** [comment]
I have attached a screenshot of the error console after requesting to sync a collection .

I notice it says "no valid items to sync" in there.

It's only existing entries in zotero that aren't synced, i.e. updates. If I add a new paper to zotero it DOES sync.

<img width="641" alt="Skærmbillede 2024-10-01 115608" src="https://github.com/user-attachments/assets/f7b94f90-a50e-4723-96c5-4611d6764dcf">

**Comment by dvanoni** [comment]
> I notice it says "no valid items to sync" in there.

The "No valid items to sync" message there is a bit misleading. It's referring to the "Notified of modify item" on the line above, which itself is referring to the Notion link attachment that's updated upon sync. All to say, that message should be okay.

> It's only existing entries in zotero that aren't synced, i.e. updates. If I add a new paper to zotero it DOES sync.

Are you saying it doesn't sync any property changes when you update an item, or is it specifically just updates to notes that don't sync?

**Comment by vpninfodk** [comment]
No updates for existing entries are synced.

New entries are synced but only "basic info" so not notes I create when the entry is imported to zotero.

**Comment by dvanoni** [comment]
@vpninfodk what happens when you right-click on a note item and select "Sync to Notion?" Do you see an error?

**Comment by vpninfodk** [comment]
Tried syncing a collection with five items. 

- It looks like all five items are synced but for two of them neither title nor authors are synced at all so they're empty in notion.
- Notes aren't synced for any items.

![image](https://github.com/user-attachments/assets/18f80a10-c41a-40bf-8a91-0bf758f86400)

Then I tried syncing a note and it appears to run as expected but the note doesn't show up in notion:

![image](https://github.com/user-attachments/assets/4b83fbbd-8f44-4339-ab33-b6111e0487b9)

Tried syncing another collection which gives this error. Is the plugin trying to sync to the wrong database here?

![image](https://github.com/user-attachments/assets/0c2fe21d-3cd1-4af0-8916-aeb1adf88368)

**Comment by dvanoni** [comment]
> It looks like all five items are synced but for two of them neither title nor authors are synced at all so they're empty in notion.

Could you try syncing one of those two items and then, in the error console, expand the message that starts with `Update page`? I'd be curious to see what the values look like for `Title` and `Authors`.

> Then I tried syncing a note and it appears to run as expected but the note doesn't show up in notion

It does indeed look like it synced the note content. If you look at the page for that note's parent item in Notion, is the page empty? There's no "Zotero Notes" heading at all?

> Tried syncing another collection which gives this error. Is the plugin trying to sync to the wrong database here?

It could be something along those lines. Did you happen to sync some items into one database and then change the database in Notero preferences? There's currently a bug (#241) with that process.

Another possible cause could be if you deleted the page for that item in Notion. Either way, I think you should be able to remedy that by deleting the Notion link attachment on that item in Zotero.

**Comment by vpninfodk** [comment]
Tried syncing one of the "faulty" items and here's the error console. The
Title and authors are correct but the fields remain empty in notion.
[image: image.png]

"Notes" remains empty and there is no "Zotero notes" property available.

I have changed databases a few times to fix the problem by creating a new
database in notion and linking to that one.

**Comment by dvanoni** [comment]
Would you mind sending that screenshot again in GitHub directly? Unfortunately screenshots don't come through in email replies.

Changing the database multiple times could certainly be causing issues here because of #241. What could be happening is that data is being synced to the pages in the old databases instead of the latest one you've selected. In order to ensure items sync to the latest database, you'll need to delete the Notion link attachment on an item before syncing it.

**Comment by vpninfodk** [comment]
Here it is:

![image](https://github.com/user-attachments/assets/c281638f-ee2a-415d-864d-6705da3a0dde)

I tried deleting the notion link attachments in zotero and sync the collection. It syncs but duplicates items in notion instead of updating them. 

I have all properties shown on notion but still no sign of zotero notes.

Can I start from scratch by deleting all the notion link attachments in zotero and setting up a connection to a new database in notion?

**Comment by dvanoni** [comment]
> Can I start from scratch by deleting all the notion link attachments in zotero and setting up a connection to a new database in notion?

Yes, I do believe that should reset things. Let me know how it goes!

I'm still stumped about the notes not appearing at all, especially since the logs definitely showed the sync happening. I'm curious if the reset helps at all.

**Comment by vpninfodk** [comment]
Did the reset and now items sync correctly to the new database except for the notes, they still don't show up. From the console they appear to be synced but don't show up in notion. I have all properties shown and nothing.

Am I missing something here like manually adding the zotero note in notion or something like that?

![image](https://github.com/user-attachments/assets/1515d1ad-ccb3-4616-8b7e-97489bb80c3b)

**Comment by dvanoni** [comment]
> Am I missing something here like manually adding the zotero note in notion or something like that?

No, I don't think you're missing anything. You don't need to manually add the note to Notion.

Just to confirm, when you open one of the Notion pages that's supposed to have notes, it's completely empty?

**Comment by srenwhlgrn** [comment]
As far as I can tell there's not even a note property available in notion.

![image](https://github.com/user-attachments/assets/67b3b08b-51cb-453b-9242-1d67bdd62597)

 I tried making a new notion user and db and sync to that to see if the issue was on that side but it's still the same problem even though everything appears to be running smooth according to the console.
 
 
![image](https://github.com/user-attachments/assets/336eaa8f-b53a-459a-a729-b8d04cfbe02d)

**Comment by dvanoni** [comment]
That's correct. Notes are not synced as a property. They're synced as content within the page itself under a "Zotero Notes" heading.

Example:

![CleanShot 2024-10-03 at 08 08 06@2x](https://github.com/user-attachments/assets/e69908b8-c3ff-48b8-9e0e-749cf56c3fc1)

**Comment by srenwhlgrn** [comment]
How do I access that view?

**Comment by dvanoni** [comment]
To view a page in a database, you click the "Open" button on its name. If notes synced as expected, there should be a "Zotero Notes" toggle heading which you can open by clicking the arrow to the left of the heading.

https://github.com/user-attachments/assets/b536cfdb-552b-43c8-987c-9ca0beffd590

**Comment by dvanoni** [comment]
Syncing notes as a database property is not yet supported. It's also been requested previously, so I just created #590 to track that. Please follow that issue and add any input you have!

Are you good with closing this one?

**Comment by vpninfodk** [comment]
Sorry, man, my bad. I was using this fork with notes sync and thought it was yours.

https://github.com/makinteract/notero-notes

But thanks for helping me solve the other issues! And yes, you can close it. :)

Thanks for both help and plugin!
