### ISSUE TITLE
Issue with syncing one particular article

### ISSUE THREAD

**Issue by Hochinwei** [dvanoni/notero#586]
Syncing problem with one of my articles in Zotero. I have the pdf uploaded onto Zotero and can see the relevant descriptions labelled on Zotero, such as author, year, doi, etc. 

![image](https://github.com/user-attachments/assets/0b07447e-89b9-413c-9e69-29b1f663e6fa)

However, when I sync the item (right-click and press "sync to notion", it tries to sync in notion, but the following error shows up:

![image](https://github.com/user-attachments/assets/308fe0bf-c3f6-41ce-9a3f-34a710aad70c)

I am perplexed as the notion URL is there under my item in zotero still.

Any and all advice is appreciated, thank you!

**Comment by dvanoni** [comment]
Hi @Hochinwei, thanks for reporting this!

I may know what's going on here. Did you happen to sync this item into one database and then change the database in the Notero preferences?

I've seen this happen before when an item is synced into a database that doesn't contain most of the properties, and then the Notero preferences are updated to point to a database that has the properties. It's related to #241 in that the item still tries to sync to the previous database even though the database setting in Notero preferences has been changed.

To hopefully resolve it, you can try deleting the Notion link attachment under your item and then perform the sync again. Let me know if that helps!

**Comment by Hochinwei** [comment]
Hello @dvanoni, thank you so much for your help!

I deleted the notion link attachmenet under the item as you've recommended and resynced the item into notero again with no issues at all.

Appreciate the advice!
