### ISSUE TITLE
Can't Sync Items to Notion

### ISSUE THREAD

**Issue by Hetian97** [dvanoni/notero#589]
Thank you for your work and generous sharing!
It has been working well, but this morning it was unable to sync items from Zotero to Notion and there were no popups.
BTW, I have the latest version of Notero - 0.6.4
Here's the screenshot. Hope it's helpful. 
<img width="648" alt="屏幕截图 2024-10-04 141858" src="https://github.com/user-attachments/assets/6ee1c92e-07e4-485f-90c3-64c354792fe8">

![屏幕截图 2024-10-04 144719](https://github.com/user-attachments/assets/420163aa-df9c-4ac6-b9e5-a3c8bbabcf78)

Thanks.

**Comment by dvanoni** [comment]
Hi @Hetian97, thanks for sharing those screenshots! I see in the first one there's an issue with with Notero trying to use the console, but I'm not sure what's causing it.

If you quit Zotero and reopen it, do you still encounter the same issue?

I'm also wondering if there's another plugin that's creating some sort of conflict. Do you have other plugins installed?

**Comment by Hetian97** [comment]
I've exited and reopened Zotero several times, but it still doesn't work.

![image](https://github.com/user-attachments/assets/ecf151a5-1f60-4d4d-90a5-e84ce4cf7a83)
![image](https://github.com/user-attachments/assets/761c6d2a-1dd5-4c6b-ab77-c32a34273ba2)
![image](https://github.com/user-attachments/assets/46e44317-8f84-4bcc-83e4-918b81366702)

**Comment by Hetian97** [comment]
I tried disabling all the other plugs and the syncing works! I don't know which one is creating the conflict with Notero. Maybe I can enable them one by one and see which one creates a conflict.
Many thanks!

**Comment by dvanoni** [comment]
Thanks for debugging! If you determine which plugin is causing the issue, please let me know. If I can find the code for it, maybe I can spot the issue and report it to the author.

**Comment by Hetian97** [comment]
I think it's Better Notes for Zotero. Notero doesn't work if I enable Better Notes for Zotero. The opposite is true if I disable it.

**Comment by dvanoni** [comment]
I reported this to the Better Notes author in https://github.com/windingwind/zotero-better-notes/issues/1152

**Comment by Hetian97** [comment]
Yes, it is fixed! Thank you!
