### ISSUE TITLE
Not sync zotero to notion

### ISSUE THREAD

**Issue by Sherryan8** [dvanoni/notero#591]
Hello, I have Zotero, version => 7.0.7 (x64), os => macOS 15.0.1, extensions => Notero (0.5.17, extension), Ethereal Style (4.9.8, extension, disabled).
I duplicated "Notero Basic" template and connected it with the "For Zotero" integration.
For Notero add-on, the integration token is right and database is "Notero Basic" automatically.

**To Reproduce**
Right click on a library or an article and choose "sync to Notion", nothing happens in the notion page with a pop-up of syncing items to Notion... 
![image](https://github.com/user-attachments/assets/40ca67e0-0733-4ba0-96eb-ed6cb00c7ee6)

![image](https://github.com/user-attachments/assets/5808c928-9b0f-49c5-941d-707b2fe77f94)

![image](https://github.com/user-attachments/assets/18da129d-9876-4f45-831f-9676f53b8ed0)

I have tried to reinstall Zotero, to upgrade Notero to the lasted version, and to duplicate the "Notero Advanced" template. All didn't work.

**Comment by YiFraternity** [comment]
I had the same problem

**Comment by dvanoni** [comment]
Hi @Sherryan8, thanks for reporting. Would you mind updating Notero to the latest version (0.6.4) and let me know if that helps at all?

@YiFraternity, what version of Notero are you on?

If you update Notero and still see the issue, would you mind opening the Zotero error console and taking a screenshot of it when this happens? You can open the error console from the menu: Tools > Developer > Error Console

**Comment by YiFraternity** [comment]
> Hi @Sherryan8, thanks for reporting. Would you mind updating Notero to the latest version (0.6.4) and let me know if that helps at all?
> 
> @YiFraternity, what version of Notero are you on?
> 
> If you update Notero and still see the issue, would you mind opening the Zotero error console and taking a screenshot of it when this happens? You can open the error console from the menu: Tools > Developer > Error Console

The version of Zotero is 7.0.7-beta.4+304e76685 (64-bit), and the version of Notero is 0.6.4.

**Comment by Sherryan8** [comment]
> Hi @Sherryan8, thanks for reporting. Would you mind updating Notero to the latest version (0.6.4) and let me know if that helps at all?
> 
> @YiFraternity, what version of Notero are you on?
> 
> If you update Notero and still see the issue, would you mind opening the Zotero error console and taking a screenshot of it when this happens? You can open the error console from the menu: Tools > Developer > Error Console

I updated to Notero (0.6.4, extension), still not working.

**Comment by dvanoni** [comment]
@YiFraternity, thanks for sharing the logs! I can see you're encountering the same issue that was reported in #589.

It turns out that issue was caused by v2.0.10 of the Better Notes plugin, and they fixed it in v2.0.11. See https://github.com/windingwind/zotero-better-notes/issues/1152

Are you using Better Notes? If you update Better Notes to the latest version and then restart Zotero, does that fix the issue for you?

@Sherryan8, are you encountering the same issue?

**Comment by Sherryan8** [comment]
> ，感谢您分享日志！我可以看到您遇到了与 #589 中报告的相同问题。
> 
> 事实证明，该问题是由 Better Notes 插件的 v2.0.10 引起的，他们在 v2.0.11 中修复了它。参见 [windingwind/zotero-better-notes#1152](https://github.com/windingwind/zotero-better-notes/issues/1152)
> 
> 您在使用 Better Notes 吗？如果您将 Better Notes 更新到最新版本，然后重新启动 Zotero，这是否能为您解决问题？
> 
> ，您是否遇到了同样的问题？

I'm not using any other extensions. If I degrade to Zotero 6, Notero 0.5.17 works well. Something is wrong with the compatibility of Zotero 7 and Notero 0.6.4.

**Comment by dvanoni** [comment]
Thanks for the info, @Sherryan8. Can you attempt a sync in Zotero 7 and then send a screenshot of the error console? I'd like to see if there's issues we can spot there.

**Comment by Sherryan8** [comment]
> Thanks for the info, @Sherryan8. Can you attempt a sync in Zotero 7 and then send a screenshot of the error console? I'd like to see if there's issues we can spot there.

This is the screenshot. Thanks.
<img width="893" alt="截屏2024-10-06 上午11 10 02" src="https://github.com/user-attachments/assets/c2fa4e23-2c8f-465c-a706-7c9862fdc288">

**Comment by YiFraternity** [comment]
> > ，感谢您分享日志！我可以看到您遇到了与 #589 中报告的相同问题。
> > 事实证明，该问题是由 Better Notes 插件的 v2.0.10 引起的，他们在 v2.0.11 中修复了它。参见 [windingwind/zotero-better-notes#1152](https://github.com/windingwind/zotero-better-notes/issues/1152)
> > 您在使用 Better Notes 吗？如果您将 Better Notes 更新到最新版本，然后重新启动 Zotero，这是否能为您解决问题？
> > ，您是否遇到了同样的问题？
> 
> I'm not using any other extensions. If I degrade to Zotero 6, Notero 0.5.17 works well. Something is wrong with the compatibility of Zotero 7 and Notero 0.6.4.


Thanks for your share.

**Comment by dvanoni** [comment]
Thanks for sharing that screenshot, @Sherryan8. I'm not sure exactly what the issue is, but based on the logs I have a hunch that it may be related to exporting citations.

What Item Format are you using for Quick Copy in the Export settings? (See screenshot.) If you try changing to a different format, does that help at all?

![CleanShot 2024-10-05 at 22 45 17@2x](https://github.com/user-attachments/assets/6f677247-29ef-4206-b494-cbaa40e38651)

**Comment by Sherryan8** [comment]
> Thanks for sharing that screenshot, @Sherryan8. I'm not sure exactly what the issue is, but based on the logs I have a hunch that it may be related to exporting citations.
> 
> What Item Format are you using for Quick Copy in the Export settings? (See screenshot.) If you try changing to a different format, does that help at all?
> 
> ![CleanShot 2024-10-05 at 22 45 17@2x](https://private-user-images.githubusercontent.com/299357/373924792-6f677247-29ef-4206-b494-cbaa40e38651.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjkxMzYsIm5iZiI6MTcyODIyODgzNiwicGF0aCI6Ii8yOTkzNTcvMzczOTI0NzkyLTZmNjc3MjQ3LTI5ZWYtNDIwNi1iNDk0LWNiYWE0MGUzODY1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxNTMzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzVhZmEzNzAyMmI2M2RkOThkZWJmNzAzMjE3Mjc3MDU5NjdlMjIyOTI2ZWZmZjAwNzlkYjQxMzViOGQ5MzhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UHkVA6J-hX6JDZe4tK0PqF8pkdxcgTBuiiw5wfT52Z4)

You are right, the format Quick Copy does affect the syncing. 
The format I'm using is Better BibTex Citation Key Quick Copy. I tried changing to different formats. With some formats, still nothing happened after request of syncing. With some other formats, record was synced to notion with unreadable codes and blank contents.

**Comment by dvanoni** [comment]
Thanks for confirming, @Sherryan8.

If "Better BibTex" options are available for export formats, does that mean you also have the Better BibTeX plugin installed? If you don't have it installed, could you try installing the latest version of it to see if that helps with using those formats?

**Comment by Sherryan8** [comment]
> Thanks for confirming, @Sherryan8.
> 
> If "Better BibTex" options are available for export formats, does that mean you also have the Better BibTeX plugin installed? If you don't have it installed, could you try installing the latest version of it to see if that helps with using those formats?

I installed the lasted version of Better BibTex, it does work now! Thank you so much! 
I had blank contents in my previous try was because I changed the language of the notion template. Only English works.

**Comment by dvanoni** [comment]
Great! I'm glad it's working!

And yes, you're correct. The Notion property names only work in English right now, but I'm hoping to make that customizable soon.

Are you good with closing this issue?

**Comment by Sherryan8** [comment]
Thank you. I will close the issue.

**Comment by p535fans** [comment]
Change the item as follow, it works.
<img width="428" alt="Image" src="https://github.com/user-attachments/assets/f67dc93d-5133-492e-b815-05fb2c3b6232" />
