### ISSUE TITLE
Cannot sync to Notion

### ISSUE THREAD

**Issue by DelmarHuang** [dvanoni/notero#598]
Followed the instruction to finish all steps but still failed to sync. 

# Settings

1. Created an integration in Notion

<img width="910" alt="image" src="https://github.com/user-attachments/assets/7528d887-2e39-4e13-9b42-894c6a94f9a2">

2. invited it into Notion template copied from you

<img width="1194" alt="image" src="https://github.com/user-attachments/assets/f4aae33d-9ba5-49b2-b4d9-e652e1f07da5">

3. Installed the plugin, pasted the integration token, and enabled sync

<img width="800" alt="image" src="https://github.com/user-attachments/assets/ff68914c-9469-48d0-a363-c9f409fbd1ab">

# Versions

- Zotero: 7.0.7
- Notero: 0.6.4
- Notion client: 3.15.0 (eff12ca)
- Notion: 2.44.23.13.0.503

# Reproductions

1. Right clicked on the collection "Books", and clicked on "Sync Items to Notion". Nothing happened.

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/c90ba7f1-ba78-40a5-91f8-a253e21cbcfc">

2. Right clicked on the book "Venture Deals", and clicked on "Sync to Notion". Nothing happened.

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/500f8ad5-c21d-49c1-adbe-d3740af61fa7">

3. Right clicked on other items, such as the selected note whether or not it is in the synced collection, and clicked on "Sync to Notion". Said "Cannot sync note for item that is not synced."

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/8c6e591f-2b29-45ac-a445-590ee7380ffc">

Please help! @dvanoni Thanks a lot!

**Comment by dvanoni** [comment]
Hi @DelmarHuang, thanks for the thorough issue report!

Would you mind sending one more screenshot of the Error Console when you try to sync? You can open it from the menu: Tools > Developer > Error Console

Also, I see you have the Better Notes plugin installed. Are you on the latest version of that? There was a bug in v2.0.10 of Better Notes that broke Notero. (See #589)

**Comment by DelmarHuang** [comment]
@dvanoni Thanks for your reply!

the better notes plugin version is 2.0.14 which I downloaded today.

for the error, please have a look below.

- sync the folder: 

<img width="900" alt="image" src="https://github.com/user-attachments/assets/5c5b818b-7579-4aea-a075-89183daae01d">

- sync the book:

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/6dc29c47-2fc9-4054-8cd9-ae19b32dcaf1">

Please tell me if you need any other screenshots!

**Comment by DelmarHuang** [comment]
one more, this is the error when I tried to sync the note created by better notes plugin, whether or not the mentioned note is in the collection. 

<img width="900" alt="image" src="https://github.com/user-attachments/assets/e40149de-d5c9-4586-bd49-26ad82004e33">

**Comment by dvanoni** [comment]
Thank you, @DelmarHuang! I see what's happening.

The "Venture Deals" item appears to be a PDF, which in Zotero is known as an "attachment" item. Notero only supports syncing "regular" items, so you'll need to add a parent "regular" item for that PDF. You can do that by right-clicking on the PDF item and selecting "Create Parent Item..." Once you've done that, I believe you should be able to sync it, but please let me know if it still doesn't work.

As for the note item, that's a similar issue. Notero syncs note items as content of the Notion page for the parent "regular" item. In this case, this note does not have a parent regular item, so Notero doesn't have a page to sync it to in Notion.

Let me know if this helps!

**Comment by DelmarHuang** [comment]
@dvanoni it works now!! But one more question, it doesn't sync attachments, such as PDF, and annotations, right? I need to turn the annotations into item notes (not standalone note) in order to sync with Notion? Thanks!

**Comment by dvanoni** [comment]
I'm glad it's working, @DelmarHuang!

And yes, you have to create a note from the PDF annotations in order to sync them. Unfortunately, Notion doesn't allow uploading files via their API, so this is the best we can do right now.

**Comment by DelmarHuang** [comment]
Great! Thank you!

Warm regards,
Delmar
