### ISSUE TITLE
Support multiple collection and subfolders?

### ISSUE THREAD

**Issue by panyuz** [dvanoni/notero#6]
Can you support multiple collection and subfolders?

**Comment by theotheo** [comment]
What do you think about this issue's suggestion? Do you plan it to implement yet?  I have a huge amount papers and books (~10k) in my Zotero separated in a lot collections. So it would be great to be able sync multiple collections. I'm even thinking of doing it myself, but not sure how long it would take.

p.s. @dvanoni thank you for Notero. It's a game changer!

**Comment by dvanoni** [comment]
Hi @theotheo, I'm glad you're finding Notero useful!

Yes, I think this is a great suggestion, and it's definitely on my todo list. I think this issue has the most 👍🏻 of any, so I know it's something that folks want!

It's one of the more involved features to build, so it will take me some time, but I do believe it should be feasible. As part of this work, I'm also thinking of changing the preferences to allow you to select from your existing collections instead of having to type the name of each collection you want to sync. This should prevent any issues caused by typos, and it should allow syncing to keep working even if you rename collections.

**Comment by panyuz** [comment]
> Hi @theotheo, I'm glad you're finding Notero useful!
> 
> Yes, I think this is a great suggestion, and it's definitely on my todo list. I think this issue has the most 👍🏻 of any, so I know it's something that folks want!
> 
> It's one of the more involved features to build, so it will take me some time, but I do believe it should be feasible. As part of this work, I'm also thinking of changing the preferences to allow you to select from your existing collections instead of having to type the name of each collection you want to sync. This should prevent any issues caused by typos, and it should allow syncing to keep working even if you rename collections.

Thank you for your dedication to this powerful plugin.
If it is possible to sync multiple folders to notion, would it be possible to add a field in notion to label the source of the entries? such as "Collection"?

**Comment by dvanoni** [comment]
> If it is possible to sync multiple folders to notion, would it be possible to add a field in notion to label the source of the entries? such as "Collection"?

@panyuz I think this is a great idea, and it was also [mentioned by someone in the Zotero Forums](https://forums.zotero.org/discussion/comment/393439/#Comment_393439), so I'm glad you brought it up to remind me of it!

**Comment by dvanoni** [comment]
Here's a preview of what I've been working on for configuring multiple collections in preferences. Feedback welcome!

https://user-images.githubusercontent.com/299357/149283181-f5e837cc-b565-4f8a-83a1-fc12e306b74d.mp4

**Comment by dvanoni** [comment]
A question for folks while I'm thinking about it: would it be useful to have an "include subcollections" checkbox for each mapping?

For example, say I had this checked for the `Inbox` collection in my example above. That would make it so that items in any of the collections starting with `Sub` here would be synced to the same Notion database (`679a3...`).

**Comment by theotheo** [comment]
1) The video looks very nice for me! It it possible to search by collection name with this drop-down list? It's certainly not required thing, but nice to have, because I have a lot of collections.
2) I guess the checkbox would be very helpful at my workflow. For example, I have a collection for my master thesis, which 
contains dozen subcollections. 

P.S.
To be honestly can't wait to use this feature. I literally check this issue every day. LOL

**Comment by dvanoni** [comment]
Thanks for the feedback, @theotheo! I'm glad you're excited for this, and I appreciate your patience! 😄 

1. I was thinking of making the collection dropdown properly searchable, but that's going to be a bit more work. In hopes of getting this functionality out to you sooner, I'll probably save that for later. In the meantime, you can at least type the first few characters to jump to a collection (as you can with any dropdown), but unfortunately it doesn't really work for subcollections.
  
   https://user-images.githubusercontent.com/299357/149357296-5b42540c-9784-42af-a83f-9742a1b210de.mp4

2. That's just the kind of use case I was imagining it would support. I should be able to make that happen.

**Comment by theotheo** [comment]
I'm sure this behavior of dropdown is totally enough! Anyway anyone could just scroll by hands -- not a big deal! :) 
Btw, let me know, If you have another questions I will be glad to assist. For example, I could be a kind of beta-tester if it would be helpful.

**Comment by panyuz** [comment]
> A question for folks while I'm thinking about it: would it be useful to have an "include subcollections" checkbox for each mapping?
> 
> For example, say I had this checked for the `Inbox` collection in my example above. That would make it so that items in any of the collections starting with `Sub` here would be synced to the same Notion database (`679a3...`).

Your design is wonderful.Thank you for all your efforts. I think it would be very useful to add a "Include subcollections" option


At the same time, I also think the drop-down list approach is sufficient

**Comment by dvanoni** [comment]
@theotheo I'd greatly appreciate it if you'd like to beta test! I can post a test build here in this issue thread when I have something ready.

@panyuz I was thinking more about your suggestion to add a `Collection` property, and I realized there's a couple different ways to handle it. I've broken it out into a separate issue (#30) so it can be discussed in more detail. And because it has the potential to get a bit more involved, I'll probably work on it as a follow-up to this issue.

**Comment by dvanoni** [comment]
Not to throw a curveball here, but I wanted to get thoughts on this: if we add a `Collection` property that indicates which collection(s) an item is in, would it be simpler to allow syncing to only a single Notion database? Then you could make custom database [views](https://www.notion.so/help/views-filters-and-sorts) or [linked databases](https://www.notion.so/help/linked-databases) to work with that single Notion database however you'd like.

The idea here would be to:
- Make the implementation and preferences simpler
- Have a single source of truth in Notion that more closely mirrors how Zotero stores data

_Or_ do you all feel that it would be critical to be able to sync to completely separate Notion databases?

**Comment by panyuz** [comment]
> Not to throw a curveball here, but I wanted to get thoughts on this: if we add a `Collection` property that indicates which collection(s) an item is in, would it be simpler to allow syncing to only a single Notion database? Then you could make custom database [views](https://www.notion.so/help/views-filters-and-sorts) or [linked databases](https://www.notion.so/help/linked-databases) to work with that single Notion database however you'd like.
> 
> The idea here would be to:
> 
> * Make the implementation and preferences simpler
> * Have a single source of truth in Notion that more closely mirrors how Zotero stores data
> 
> _Or_ do you all feel that it would be critical to be able to sync to completely separate Notion databases?

My initial idea for synchronizing sub-collections was that all entries were synchronized to the same database, so a "collection" was needed to describe the source of the documents.

But after reading your synchronization logic, I think this need is redundant and I can solve this problem by synchronizing it to a different database.

From my personal point of view, the "collection" property can be put in the future development plan, if more users are interested.

**Comment by dvanoni** [comment]
To illustrate a bit more, here's an example of what I think we'd have to do to support syncing to multiple databases in the manner that I showed in my video above.

<img width="201" alt="CleanShot 2022-01-14 at 00 33 04@2x" src="https://user-images.githubusercontent.com/299357/149468953-89e57a6e-3728-44ed-a5bf-8db5e2422603.png">

In order to keep track of the Notion pages in each database, we'd need to create a separate link attachment for each page. I think this is possible, but it does make the implementation more complicated.

There's also the fact that, since these would end up being separate pages in different databases in Notion, any additional properties or body content you add to one page would not be reflected across all of them (unless you use synced blocks). I suppose this may or may not be desired depending on your use case.

I'm wondering if something more along these lines would be simpler... Instead of having to add a new "mapping" for each collection, you could just enable syncing to your one Notion database for whichever of your existing collections you wanted.

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/299357/149472758-8a4578e7-9bb3-4951-b6bc-e4c963fae812.png">

I imagine this would make the implementation of this preferences screen a bit more complicated because we'd have to build the same collections tree that the main Zotero window has, but it might make the actual syncing logic a bit simpler. The downside of course is that it's less flexible because you can only specify the single database.

I could go either way, but I just wanted to throw this idea out there to see what folks think. Keep the feedback coming!

**Comment by panyuz** [comment]
I think I understand where you are coming from. The literature may be in a different zotero collection. In this case, I think it would be more appropriate to sync to one database. As in my previous question #27 , multiple notion links increase the likelihood of synchronization errors.

**Comment by dvanoni** [comment]
@panyuz you bring up a great point about the issue in #27. I think trying to attach multiple Notion links to items has the potential to exacerbate that problem.

With that in mind, I think I'm going to rework what I have right now to sync to a single database instead of multiple. That should simplify the syncing implementation and hopefully cause fewer issues.

**Comment by theotheo** [comment]
To be honest, I can't think of a case where it would be necessary  to synchronize with multiple databases. Could someone give me an example? I guess I didn't take something into account in my imagination.

**Comment by dvanoni** [comment]
The only case I can really think of is if you were managing two completely separate projects in Notion and wanted each of them to have their own "references" database that was synced from Zotero. But to be honest, I think the "Notion way" of achieving this would be to have a single database for references and then create a linked database for each project filtered by whatever properties you need (like `Collection`).

**Comment by theotheo** [comment]
> I think the "Notion way" of achieving this would be to have a single database for references

Exactly! I'm totally sure here. I think limiting work to few databases is so say the main tendency at Notion usage.

**Comment by dvanoni** [comment]
@theotheo @panyuz I've pushed up an implementation of multi-collection syncing. If you'd like to beta test, you should be able to download the test build from the bot comment above.

The preferences page now lets you configure multiple collections with this interface:

<img src="https://user-images.githubusercontent.com/299357/149654365-7ca354f7-cde1-4805-9859-7d36b9c8425f.png" alt="Notero Preferences" width="500px" />

If you end up trying it out, please let me know how it works for you!

**Comment by panyuz** [comment]
Thank you for your excellent work, I have downloaded and tried it.  But, what is the "collection" property in the notion database?

**Comment by panyuz** [comment]
Adding literature to the watch folder creates duplicate entries in notion.

https://user-images.githubusercontent.com/4372695/149666534-8b551750-4869-430f-9a6e-ea031972a07e.mp4

**Comment by eioe** [comment]
Thanks for the work on this important feature @dvanoni ! I'm so much looking forward to having it. 

> To be honest, I can't think of a case where it would be necessary to synchronize with multiple databases. Could someone give me an example? I guess I didn't take something into account in my imagination.

I am working in multiple notion workspaces for different projects. If notero syncs to one central notion DB, I could only sync to one of them, I assume, as it's not possible to create linked DBs across workspaces. So for me, syncing one Zotero collection to one notion db would be preferred.

**Comment by theotheo** [comment]
@eioe thank you! I imagined that the discussion was about synchronization one collection with multiple databases, i.e. about 1-to-many relationship. Your "1-to-1" case is more understandable to me.

@panyuz I've faced with the same duplication issue. Thank you for the video report!

**Comment by dvanoni** [comment]
@panyuz and @theotheo, thank you for testing!

> But, what is the "collection" property in the notion database?

Adding the `Collection` property is going to require some more work, and it isn't in the test build yet. I believe I have some pieces in place for it, but I want to get the initial support for multiple collections working well first. I'll post progress updates on that in #30.

> Adding literature to the watch folder creates duplicate entries in notion.

Thanks for sharing the video of this issue! @panyuz I noticed you're using ZotFile, and I'm wondering if that may be contributing to the issue when it renames files. @theotheo are you using ZotFile as well? It looks like I'm able to reproduce the duplication issue when I have ZotFile enabled. I'll dig into this!

---

> I am working in multiple notion workspaces for different projects. If notero syncs to one central notion DB, I could only sync to one of them, I assume, as it's not possible to create linked DBs across workspaces. So for me, syncing one Zotero collection to one notion db would be preferred.

@eioe thanks for sharing your use case! That definitely makes sense. As far as I know, a Notion integration can only be connected to one workspace, so I believe your use case would require setting up a new Notion integration for each workspace that you want to use Notero for. That would mean you'll have a different integration token for each workspace, and I'd need to build more robust support to handle that. I can create a new issue to track this.

_Screenshot from Notion integration setup:_

<img src="https://user-images.githubusercontent.com/299357/149676372-3496b784-0c64-4455-bec9-81e5c5d18540.png" alt="Notion integration" width="467px" />

**Comment by dvanoni** [comment]
After some more testing, I don't think ZotFile is causing the issue. It doesn't look like renaming files causes Notero to sync again. I believe it's just Zotero itself downloading information for the item and updating it.

I think what's happening is that Zotero can sometimes update an item multiple times in short succession, and the subsequent updates can cause Notero to sync before the initial sync has finished and added the Notion link attachment required to prevent duplicates.

I'm going to try introducing a debounce to the syncing to hopefully fix this issue.

**Comment by theotheo** [comment]
Yes, I use ZotFile too!  
I've tried to update entries with and without attachments expecting to notice the difference. But I've couldn't make the connection between entry duplication and attachments. 

Maybe It depends on amount Zotero entries? I think I have too much entries and Zotero is kind of slow.

**Comment by theotheo** [comment]
By the way, do I understand correctly that subcollection sync doesn't implemented yet?

**Comment by dvanoni** [comment]
> Maybe It depends on amount Zotero entries? I think I have too much entries and Zotero is kind of slow.

That could be. I'm currently investigating the timing of events that occur in an effort to figure out what's causing the duplication issue.

> do I understand correctly that subcollection sync doesn't implemented yet?

It is implemented, but not in the way that I described earlier using an "include subcollections" option. Instead, every collection—including subcollections—is listed on its own line, and you have to select each one to sync individually. This ended up being this easiest way to implement it for now.

For example, if I wanted to include all subcollections under `Untitled 8` in the screenshot below, I'd have to select each one as shown here.

<img src="https://user-images.githubusercontent.com/299357/149801691-50320e50-e388-4395-90f5-843c5cda6605.png" alt="Syncing subcollections" width="500px" />

**Comment by 4Urban** [comment]
Thank you for awesome feature, in advance!

After updating to below test build version, sync from Zotero to one Notion db works well regardless of collection.

> 🤖 this is your friendly neighborhood build bot announcing [test build 0.2.2.48](https://github.com/dvanoni/notero/releases/download/builds/notero-0.2.2.48.xpi) ("feat: Migrate preferences from single collection to multiple")
> 
> Install in Zotero by downloading [test build 0.2.2.48](https://github.com/dvanoni/notero/releases/download/builds/notero-0.2.2.48.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

However, I fail to fill in the 'Collection' column, which I inserted new one into the notion db that has synced. Like your photo below. 

Though after adding a **Multi-select** property with the name `Collection`, it only (unlike other columns) doesn't sync.

Do I need some more steps?

> Thinking through this, I believe using a **Multi-select** property for `Collection` is going to work best.
> 
> For example, consider the following setup:
> 
> <img alt="Collection sync example" width="396" src="https://user-images.githubusercontent.com/299357/149458959-f3fafd81-031b-4ff7-b76c-9402a5f13e09.png">
> 
> Say we have both the `Paper A` and `Paper B` collections configured to sync to the same Notion database and "include subcollections" is enabled. We could have items that exist in multiple subcollections, and we'd want to reflect that when the item is synced to Notion. A **Multi-select** property seems like the best way to achieve that.
> 
> Additionally, it would be ideal for this to be robust to moving or renaming collections, and we should be able to achieve that by correlating Zotero collection IDs with Notion multi-select option IDs.

**Comment by dvanoni** [comment]
@4Urban thanks for testing! Syncing the `Collection` property isn't in this build yet because it's going to require some more work. I'll be tracking progress on it in #30.

The screenshot I posted above showing the `Collection` column in Notion was just an example I put together by adding those collections into Notion by hand, so I apologize if that caused confusion.

**Comment by 4Urban** [comment]
@dvanoni Aha, I understood. It was my mistake not reading carefully.

Anyway, I really appreciate your splendid work! Thank you!

**Comment by dvanoni** [comment]
@panyuz @theotheo the above test build includes an improvement to the syncing algorithm. Would you mind testing it to see if it fixes the issue with duplicate pages?

Note that it introduces a 2-second delay between an item being modified and starting the sync, so you'll see the "Syncing items to Notion..." message appear a little later than it was before.

**Comment by theotheo** [comment]
Thank you! I will try!

**Comment by theotheo** [comment]
So. I didn't have time to use it properly, but I haven't notice any more duplication. The last one was at 2.2.48 build.  Nice!
Просто скриншот для подтверждение

Just a screenshot with last papers
![image](https://user-images.githubusercontent.com/1499744/150345830-0187b988-7670-4ce2-8c3b-d62ae2365332.png)

**Comment by panyuz** [comment]
If you add a single entry from the web, no duplicate entries appear. However, if you add documents in bulk (5 entries), duplicate entries will still appear. I think it should be emphasized in the usage instructions to avoid such usage.

In my case, I use the notion database as a summary table for reviewing the literature, so I don't need to synchronize so often.

Thank you very much for the time you put into this feature, the plugin is now very useful.

Translated with www.DeepL.com/Translator (free version)

**Comment by dvanoni** [comment]
@theotheo @panyuz thank you both for doing more testing! I think I'm going to push a PR to close out this issue, but of course feel free to let me know if anything else comes up.

@panyuz I want to continue investigating the duplication issue that you see when adding documents in bulk, but I'm going to move that conversation over to #27.

Also, regarding this point:
> In my case, I use the notion database as a summary table for reviewing the literature, so I don't need to synchronize so often.
I will use this script to batch modify an attribute of an entry for synchronization purposes.

Would a "sync to Notion" button as described in #21 solve your use case?

**Comment by dvanoni** [comment]
For those following along, syncing multiple collections (including subcollections) is now available as of v0.3.0! My thanks goes out to everyone who provided feedback!

**Comment by yukitakahashi1** [comment]
Hello @dvanoni and all! Is it possible to add multiple Notero preferences? Currently, Notero only accepts one integration token and one database ID. I want to have multiple tokens and IDs so that I can have one database for each project.

**Comment by KaorinaXu** [comment]
> Thanks for the feedback, @theotheo! I'm glad you're excited for this, and I appreciate your patience! 😄
> 
> 1. I was thinking of making the collection dropdown properly searchable, but that's going to be a bit more work. In hopes of getting this functionality out to you sooner, I'll probably save that for later. In the meantime, you can at least type the first few characters to jump to a collection (as you can with any dropdown), but unfortunately it doesn't really work for subcollections.
>    
>      
>        
>        
>    
>        CleanShot.2022-01-13.at.08.10.56-converted.mp4
> 2. That's just the kind of use case I was imagining it would support. I should be able to make that happen.

![image](https://user-images.githubusercontent.com/112464037/187364718-96e6d22d-e0e2-473e-a68f-44630f366a6b.png)
Hi @dvanoni , I just found my Notero a bit different from yours. It seems that in your view, you can create multiple Notion databases that seperately sync multiple Zotero collections. Is this view still availible?

**Comment by idontwantausernameplease** [comment]
Hello @dvanoni, can you add this feature to the guide: https://github.com/dvanoni/notero - I am not sure how to set it up :)

Thank you very much!

**Comment by dvanoni** [comment]
Hi, @idontwantausernameplease. I was hoping the description in the Notero Preferences window would explain how this works, but perhaps it could be more clear. Can you help me understand where you'd like more clarification? I want to ensure that whatever documentation I add is clear. Thanks!

**Comment by SofiCourtney** [comment]
Hi @dvanoni thanks for making this awesome plug in- it's super useful. I just installed Notero, and have synced one Notion database to a Zotero collection (database a, collection a). Now I've set up another Notero database, and would like that to sync that to another collection (database b, collection b). it seems like from this thread, that you developed this capability already, but I'm confused about how to set it up. It seems like there is only one place in the Notero preferences to add a database ID? So how would I sync to two notion databases? Sorry if this question has been answered already, I read through the thread but haven't been able to figure it out. Thanks!

**Comment by dvanoni** [comment]
Hi @SofiCourtney! It sounds like you're describing #119. While full support for multiple Notion databases isn't available yet, there is a workaround using database filters on the `Collections` field. Please take a look at #119 for more info.

**Comment by SofiCourtney** [comment]
Thank you! That is helpful. Also, did you ever add the "include subcollections" button?
