### ISSUE TITLE
Notero is no compatiable with Zotero 7.0.7

### ISSUE THREAD

**Issue by tinghua-chen** [dvanoni/notero#603]
Is it possible to use Notero with Zotero 7.0.7?

**Comment by dvanoni** [comment]
Hi @tinghua-chen, Notero should be compatible with Zotero 7.0.7. I would recommend [downloading](https://download.notero.vanoni.dev/) the latest version (v0.6.5) for the latest fixes. Does that work for you?

**Comment by tinghua-chen** [comment]
I got it. Thank you!
