### ISSUE TITLE
Imported citation not syncing

### ISSUE THREAD

**Issue by eliu318** [dvanoni/notero#610]
Hi! I’m having an issue with citations imported from the internet in .ris format. In the attached screenshot from my Zotero, you’ll see that manually entered citations sync properly (indicated with an arrow), while imported ones do not.
<img width="46" alt="Screenshot 2024-10-30 at 3 21 09 PM" src="https://github.com/user-attachments/assets/5d0b20e7-e958-4412-adcb-9cb5d03cc655">

**Comment by dvanoni** [comment]
Hi @eliu318, thanks for reporting this!

Do you see an error if you try to manually sync these items (right-click and select "Sync to Notion"), or does nothing happen?

Based on your screenshot, it also looks like you're using Zotero 6. Is that correct? If so, it might be worthwhile upgrading to Zotero 7 and the latest version of Notero, both of which contain new features and fixes.

**Comment by dvanoni** [comment]
@eliu318, are you still encountering this issue?

**Comment by eliu318** [comment]
Your solution helped! Thank you.
