### ISSUE TITLE
Notero download shows corrupted file

### ISSUE THREAD

**Issue by SueP68** [dvanoni/notero#614]
**Describe the issue**
I am attempting to download the v0.6.7 version of Notero and a pop-up appears stating that the installation attempt was stopped because the file appears to be corrupted.

**To Reproduce**

1. Go to https://github.com/dvanoni/notero/releases/tag/v0.6.7
2. Click on notero-0.6.7.xpi 

**Expected behavior**
I expected a zip folder to be downloaded with the new version.

**Screenshots**
<img width="1373" alt="Screenshot 2024-11-03 at 08 38 17" src="https://github.com/user-attachments/assets/38a7b530-c737-44ff-a67c-2976a7ea1f9c">

**Additional context**

**Comment by dvanoni** [comment]
Hi @SueP68, it looks like you're using Firefox. There's a note in the installation section of the README that describes how to download:

> Note for Firefox users: You'll need to right-click the download link and choose **Save Link As...** in order to properly download the file.

Let me know if this works for you.

**Comment by SueP68** [comment]
Hello,

Thank you for your quick response! I totally missed that piece and it has
worked (after updating my Zotero).

Thanks again,
Sue
