### ISSUE TITLE
Notes modified in notion are synchronized  back to  zotero

### ISSUE THREAD

**Issue by MrGongqi** [dvanoni/notero#619]
Is it possible to achieve two-way synchronization between zotero and notion?
That is, when I synchronize zotero entries to notion and directly modify the notes in notice, the notes in zotero will also change and be synchronized to the same notes as the notes in the notion.

**Comment by dvanoni** [comment]
Hi @MrGongqi, two-way sync is unfortunately beyond the scope of the Notero plugin, and limitations with Notion's current [webhook actions](https://www.notion.com/help/webhook-actions) prevent us from performing updates when notes are edited in the content of a Notion page. Please see [How to sync from Notion back into Zotero](https://github.com/dvanoni/notero#how-to-sync-from-notion-back-into-zotero) in the FAQ section of the README for more details.
