### ISSUE TITLE
add attributes to contain the notes stored in zotero

### ISSUE THREAD

**Issue by fredericky123** [dvanoni/notero#64]
Before using Notero to take notes, I have already taken some notes in zotero, can we also include this information when sync to Notion
Thanks！

**Comment by dvanoni** [comment]
@fredericky123 another good feature to have! We've documented that one in #4. Feel free to give it a 👍 and add any other thoughts there!

**Comment by fredericky123** [comment]
That is so great!
Thanks a ton! Hope this come true in the future!
