### ISSUE TITLE
Allow to import "Publication", "Extra" information to Notion

### ISSUE THREAD

**Issue by SCP-CN-001** [dvanoni/notero#65]
Hello,

First of all, I really appreciate your work very much. This plugin helps to smooth my research workflow significantly. I am wondering that is it possible to add the "Publication", and "Extra" information as new columns in Notion? I guess this can be enabled by adding a few lines in notero-item.ts?

I am very, very looking forward to the future updates of Notero. Thank you again for providing us with this helpful tool.

**Comment by dvanoni** [comment]
This should be possible! It sounds related to #52.

**Comment by a1576799** [comment]
Hello,

Thanks for this powerful plugin. I am wondering if those have been solved. I still can not get "Publication" as "select" or else.

Thanks

**Comment by dvanoni** [comment]
Hi @a1576799, I haven't had time to work on this yet, but I'll be sure to post an update here when I can get around to it!

**Comment by a1576799** [comment]
thank you so much.  Looking forward to it

**Comment by xinhe-github** [comment]
I am also looking forward it.

**Comment by Python-Zhou** [comment]
I am also looking forward it.

**Comment by KaorinaXu** [comment]
Looking forward too!!

**Comment by AlieZVzz** [comment]
Looking forward too!!

**Comment by HW-MLCS** [comment]
Looking forward too :) Have a nice day!

**Comment by yzy1228682367** [comment]
Looking forward too :) Have a nice day!

**Comment by lczong** [comment]
Looking forward to it!!!! Thanks!

**Comment by davidleejy** [comment]
I too support the adding of the "publication"  and "Extra" fields

**Comment by dvanoni** [comment]
Happy holidays! I've just released [v0.5.5](https://github.com/dvanoni/notero/releases/tag/v0.5.5) which adds support for syncing the following properties:

| Property Name | Property Type |
|--------|--------|
| `Date Modified` | Date |
| `Extra` | Text |
| `Place` | Text |
| `Proceedings Title` | Text |
| `Publication` | Text |
| `Series Title` | Text |

I still want to add support for customizing the properties that can be synced. I'm tracking that work in #355, so please follow along there if you're interested!
