### ISSUE TITLE
"Item type" property on notion does not pull in data from zotero

### ISSUE THREAD

**Issue by linsharon** [dvanoni/notero#76]
I just documented my process of integrating zotero and notion using notero extension. However, I did not see "item type" synchronized from zotero to notion. What can I do?

https://youtu.be/4Z_5tskdNsY?t=1434

**Comment by dvanoni** [comment]
Hi again, @linsharon!

Thanks for sharing your video! It's wonderful!

I believe the issue you're running into is simply due to capitalization. Properties in Notion are case-sensitive, so I think you just need to change `Item type` to `Item Type`. Let me know if that fixes things for you!

**Comment by linsharon** [comment]
hey David @dvanoni, thank you very much! it is fixed after following your instruction!
