### ISSUE TITLE
Extracted from PDFs

### ISSUE THREAD

**Issue by fredericky123** [dvanoni/notero#82]
Can we have one more cell including the texts "extracted from PDFs"

I have one possible solution: we add one cell named "notes from Z", namely importing all the notes stored in Zotero previously.
Since some plugins can extract notes from pdfs, then the notes can send to Notion

Thanks a ton!

**Comment by dvanoni** [comment]
Hi @fredericky123, does the proposal in #4 sound like it would address this?

**Comment by fredericky123** [comment]
Great, it will definitely solve this. Thanks @dvanoni  a ton!
