### ISSUE TITLE
doubled checked eveything, notero doesn' t sync Notion and zotero not at all

### ISSUE THREAD

**Issue by Chatshop** [dvanoni/notero#87]
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Chatshop** [comment]
<img width="635" alt="Screen Shot 2022-06-30 at 7 36 05 PM" src="https://user-images.githubusercontent.com/2265317/176795530-5cb2266f-3d35-4801-8812-746989e575ae.png">

I can't sync Zotero with Notion. The secret key and database Id are correct.

**Comment by Chatshop** [comment]
I tried again to add a tag and now I got this error



What am I doing wrong?

**Comment by dvanoni** [comment]
@Chatshop would you mind posting your new screenshots directly in GitHub rather than sending over email? It looks like the attachments didn't come through. Thanks!

**Comment by Chatshop** [comment]
hi again, here is the error message that I got.  thank you!

<img width="1440" alt="Screen Shot 2022-06-30 at 10 01 46 PM" src="https://user-images.githubusercontent.com/2265317/176883048-1a1e5efe-4bfa-4fb6-b731-6fc9bc198847.png">
.

**Comment by Chatshop** [comment]
OH MY GOD, this was a stupid mistake, but I didn’t catch it, thank you!

It works now

Line
Ps: it would be nice to have the option to sync a complete collection on the first connection

**Comment by dvanoni** [comment]
> Ps: it would be nice to have the option to sync a complete collection on the first connection

@Chatshop I completely agree! That's definitely something I want to add.

I'm glad you were able to get things working!

**Comment by Chatshop** [comment]
Great!  It is already a wonderful add-on, I love it!
