### ISSUE TITLE
Possible refresh / tag issue

### ISSUE THREAD

**Issue by neonFog** [dvanoni/notero#89]
Hi. Thank you so much, dvanoni for building and maintaining this. It's such a help.
I didn't see this addressed in the FAQ. I apologize if I am missing something.

Issue:
I connected a group directory from Zotero to a Notion database. The database would not update and pull the citations until I added the tag "notero" to the citation in Zotero. I read that the Notero plugin would add the "notion" tag to all citations within the designated folder, which it successfully does. Unfortunately, I also need to add the additional "notero" tag. 

Thanks

**Comment by dvanoni** [comment]
Hi @neonFog, thanks for reaching out!

One of the current limitations of Notero is that it won't automatically sync items once you configure it. You either have to add items to one of your monitored collections, or you have to perform a modification to an item. In your case, adding a `notero` tag sounds like it was the modification that triggered the sync.

Does this sound like what you're encountering? If so, I wonder if #21 would be useful for you once it's implemented?
