### ISSUE TITLE
sync local paths of attached files and automatically upload attached files

### ISSUE THREAD

**Issue by hengfei-wang** [dvanoni/notero#9]
Hi, 

Thank you for your work. I have used zotero for a long time. Usually, I add papers with pdf files to zotero using its Chrome extension. When I come to notion, I find notion can not link a local file. That causes a lot of trouble. Could you add local paths of attached files in sync list? If it can automatically upload attached files, that will also be great.

Advice:
Since people may have different needs on sync information, I advise to set a sync list so that users can choose the items they want to sync from zotero.

Thank you！

**Comment by dvanoni** [comment]
Hi @hengfei-wang, thanks for the feedback!

I've also found that Notion does not have a way to link to local files. It also can't link to local Zotero items using its `zotero` protocol (e.g. `zotero://select/library/items/XN4SL8R5`) which I was originally hoping to use to link directly from Notion to the Zotero desktop app. Notion can only successfully link to the `https` URLs pointing to the Zotero web app (e.g. `https://www.zotero.org/users/8888888/items/XN4SL8R5`).

The Notion API [does not currently support uploading files](https://developers.notion.com/reference/file-object#externally-hosted-files-vs-files-hosted-by-notion), so I think the best we could do for now is have a text property in Notion with the path to the local file. You'd then have to manually copy that path and open it on your system in some manner (perhaps pasting into your browser). Would that be beneficial at all?

**Comment by hengfei-wang** [comment]
Thank you for your reply. 

Yes, it is totally fine if you could add a text property including local path. I can set a shortcut in alfred to open a file from selected text.

**Comment by dvanoni** [comment]
@hengfei-wang file path syncing has just been released in version 0.2.1! You can get the file paths into Notion by adding a new **Text** property named `File Path` to your database and then syncing your items again.

Let me know how this works for you!
