### ISSUE TITLE
Notero not working when window closed on MacOS

### ISSUE THREAD

**Issue by liu-jinyu** [dvanoni/notero#90]
**Notero not working when I close and restart the Zotero window**
I'm using Zotero on m1 MacBook Air, and notero seems to stop working every time I close the Zotero window(i.e. pressing Cmd+W and reopen the Zotero window).

I can restart notero by completely closing Zotero(i.e. Cmd+Q), and restart. So I'm wondering whether other people also have this issue, is there a way to fix it?

btw, Thanks for this amazing plugin, it helped me a lot with my paper reading!

**Comment by dvanoni** [comment]
Hi @liu-jinyu, thanks for reporting this!

I've run into this same issue, and I haven't dug into it enough to figure out what a solution might be. I believe it's related to how Zotero loads plugins. I think the Zotero team is changing the process for loading plugins, and that may require me to rework how Notero loads anyways. Hopefully that will solve this issue.

**Comment by bettina-mj-kern** [comment]
I'm having the same issue on an M1 MacBook.

Also massive thank you from me for creating this plug-in. It's so insanely useful!

**Comment by greenlight2000** [comment]
same on intel MacBook pro 2019. issue fixed by restarting the Zotero

**Comment by sherlyn99** [comment]
same issue. my link/connection stops working after a while. I tried to restarting zotero but it did not work for me. I am running notero on a m2 macbook pro. I am wondering if anyone has the same issue or has a solution. Great plug-in!

**Comment by emisaghi** [comment]
> same issue. my link/connection stops working after a while. I tried to restarting zotero but it did not work for me. I am running notero on a m2 macbook pro. I am wondering if anyone has the same issue or has a solution. Great plug-in!

I have the same issue! I essentially have to disable Notero, restart Zotero, enable Notero, restart Zotero and change a tag every time. Thanks for the great plugin and I would love a fix for this issue, if someone has one.

**Comment by dvanoni** [comment]
Looks like we'll need to handle re-initialization. See [discussion with Dan Stillman](https://groups.google.com/g/zotero-dev/c/O1TGIpfAdT0/m/D5Ye66NaAgAJ):

>>  Is there a recommended approach for re-initializing things when the main Zotero window is closed and re-opened (on macOS)?
>>
>> For example, when my plugin starts up with Zotero, the `startup` function is called, and I add a menu item to the tools menu. If the Zotero window is closed and re-opened, the `startup` function is not called again, and thus my menu item is no longer in the tools menu.
>>
>> Do I need to use `Services.wm.addListener` from my `startup` function and listen for whenever the main Zotero window is opened again?
>
> For now, yes, though we could consider adding an easier hook for this in Zotero 7. (Make It Red doesn't deal with this either currently and has the same problem.)

**Comment by dvanoni** [comment]
The Zotero team has [added better support](https://groups.google.com/g/zotero-dev/c/zVn4k9dLoak) for this in Zotero 7. We'll need to update Notero to take advantage of this.

**Comment by nataliamush** [comment]
Hi all! About a week ago my my collections stopped syncing to Notion - I just noticed and tried a number of the fixes mentioned in issues here (disabling and re-enabling, totally removing and re-adding the add-on, turning off other add-ons like the LibreOffice integration) and nothing is bringing back "Sync to Notion" in the context menus! However, adding a "notion" tag seems to trigger a sync. Looking forward to the auto-sync fix!

**Comment by dvanoni** [comment]
Hi everyone, I just released a fix for this issue in [v0.4.13](https://github.com/dvanoni/notero/releases/tag/v0.4.13)!

Please give it a try and let me know if you're still having issues with Notero not working when you close and reopen the Zotero window.

**Comment by leylime** [comment]
Fixed! Thank you!! 
Notero is an absolute lifesaver - thank you so much for all you do.
